#!/usr/bin/env python3
"""
NEXT OS — Nia Brain Bundler
============================
Reads every markdown file in nia-brain/ and bundles them into
nia-brain.jsx as a JS module exposing window.NIA_BRAIN with the
document store + retrieval helpers.

Usage:
    python3 build-brain.py

Then re-inline into NEXT OS.html via the inline scripts.

When Hudson edits any .md in nia-brain/, he just runs:
    python3 build-brain.py
and refreshes the OS.

No deps. Pure Python 3.
"""
import os, json, io

ROOT = os.path.dirname(os.path.abspath(__file__))
BRAIN_DIR = os.path.join(ROOT, "nia-brain")
OUT = os.path.join(ROOT, "nia-brain.jsx")

def collect_docs(folder, prefix=""):
    docs = []
    if not os.path.isdir(folder):
        return docs
    for name in sorted(os.listdir(folder)):
        path = os.path.join(folder, name)
        if os.path.isdir(path):
            docs.extend(collect_docs(path, prefix + name + "/"))
            continue
        if not name.endswith(".md"):
            continue
        with io.open(path, "r", encoding="utf-8") as f:
            body = f.read()
        # Use the first H1 as the title, else the filename
        title = name[:-3].replace("-", " ").title()
        for line in body.splitlines():
            s = line.strip()
            if s.startswith("# "):
                title = s[2:].strip()
                break
        docs.append({
            "id":    prefix + name[:-3],
            "title": title,
            "body":  body,
        })
    return docs

docs = collect_docs(BRAIN_DIR)
print(f"Found {len(docs)} brain documents:")
for d in docs:
    print(f"  - {d['id']}: {d['title']} ({len(d['body'])} chars)")

# Build the JSX bundle. The runtime in nia-brain.jsx exposes:
#   window.NIA_BRAIN.docs                — array of {id, title, body}
#   window.NIA_BRAIN.retrieve(query, k)  — top k matching docs by score
#   window.NIA_BRAIN.systemPrompt(query) — formatted string to inject
js = f"""/* nia-brain.jsx — AUTO-GENERATED by build-brain.py
   Do NOT hand-edit. Edit the markdown files in nia-brain/ and re-run
   the bundler. */

(function () {{
  const DOCS = {json.dumps(docs, ensure_ascii=False, indent=2)};

  // Simple bag-of-words retrieval. No external deps. Stopword-aware.
  const STOP = new Set(['the','a','an','is','are','was','were','of','to','in','on','for','with','by','and','or','but','at','as','it','this','that','these','those','i','you','he','she','we','they','me','him','her','us','them','my','your','his','her','our','their','what','who','how','when','where','why','do','does','did','can','could','should','would','will','be','been','being','have','has','had']);

  function tokenize(s) {{
    return String(s || '').toLowerCase()
      .replace(/[^a-z0-9\\s]/g, ' ')
      .split(/\\s+/)
      .filter(w => w && !STOP.has(w) && w.length > 2);
  }}

  // Pre-tokenize each doc once.
  const docTokens = DOCS.map(d => {{
    const tokens = tokenize(d.title + ' ' + d.body);
    const counts = {{}};
    for (const t of tokens) counts[t] = (counts[t] || 0) + 1;
    return counts;
  }});

  function retrieve(query, k) {{
    const qTokens = tokenize(query);
    if (qTokens.length === 0) return [];
    const scored = DOCS.map((d, i) => {{
      const counts = docTokens[i];
      let score = 0;
      for (const t of qTokens) {{
        if (counts[t]) score += counts[t];
      }}
      // Title boost
      const titleTokens = tokenize(d.title);
      for (const t of qTokens) {{
        if (titleTokens.includes(t)) score += 5;
      }}
      return {{ doc: d, score }};
    }});
    scored.sort((a, b) => b.score - a.score);
    return scored.filter(s => s.score > 0).slice(0, k || 3).map(s => s.doc);
  }}

  // Build a system-prompt snippet to inject before each turn.
  function systemPrompt(query, k) {{
    const hits = retrieve(query, k || 2);
    if (hits.length === 0) return '';
    return '\\n\\n=== NIA BRAIN (your knowledge — quote and reason from this) ===\\n'
      + hits.map(d => '## ' + d.title + '\\n\\n' + d.body).join('\\n\\n---\\n\\n')
      + '\\n=== END NIA BRAIN ===\\n';
  }}

  window.NIA_BRAIN = {{
    docs: DOCS,
    retrieve: retrieve,
    systemPrompt: systemPrompt,
    count: DOCS.length,
  }};

  console.log('[Nia Brain] ' + DOCS.length + ' documents loaded.');
}})();
"""

with io.open(OUT, "w", encoding="utf-8") as f:
    f.write(js)

print(f"\nWrote {OUT} ({len(js)} chars)")
print("Next: re-inline into NEXT OS.html and refresh the OS.")
