-- Import all Kabs Lily Fees and Student Accounts into Supabase
-- Run this in the Supabase SQL Editor

DO $$
DECLARE
  v_tenant_id text := 'kabs-lily-junior-school-and-kindercare-centre';
BEGIN
  -- Delete existing financial records for clean re-import
  DELETE FROM school_income WHERE tenant_id = v_tenant_id;
  DELETE FROM fees WHERE tenant_id = v_tenant_id;

  -- Insert all fee structures & accounts for Kabs Lily into school_income
  INSERT INTO school_income (tenant_id, student_name, class, source_type, amount, unspent_balance, payment_method, received_by, notes, logged_by) VALUES
  (v_tenant_id, 'Namala Leticia', 'Baby Class', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Arinaitwe Elijah', 'Baby Class', 'School Fees (Boarding)', 350000, 250000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Ssentongo Alpha', 'Baby Class', 'School Fees (Tuition)', 390000, 190000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Blessing Namusisi', 'Baby Class', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kisakye Jemimah', 'Baby Class', 'School Fees (Tuition)', 250000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Male David Joshua', 'Baby Class', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Lataya Elvis', 'Baby Class', 'School Fees (Tuition)', 200000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssuna Traylin', 'Baby Class', 'School Fees (Tuition)', 260000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Momoa Kent', 'Baby Class', 'School Fees (Tuition)', 250000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Eady Steven', 'Baby Class', 'School Fees (Tuition)', 280000, 130000, 'Cash', 'Nalukenge Jane', 'Paid in 3 installments', 'bursar'),
  (v_tenant_id, 'Nalubwama Maria Blessing', 'Baby Class', 'School Fees (Tuition)', 230000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kirabo Wisdom', 'Baby Class', 'School Fees (Tuition)', 235000, 125000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kirabo Terisa', 'Baby Class', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mucwanya Janiel', 'Baby Class', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nabbanya Miracle', 'Middle Class', 'School Fees (Tuition)', 155000, 65000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kiberu Rohan', 'Middle Class', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssenyondo Rayan', 'Middle Class', 'School Fees (Tuition)', 200000, 125000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kalungi Jovitah', 'Middle Class', 'School Fees (Tuition)', 200000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kemirembe Dorothy', 'Middle Class', 'School Fees (Tuition)', 200000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Namatovu Skylar', 'Middle Class', 'School Fees (Tuition)', 280000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Bagonza Isaiah', 'Middle Class', 'School Fees (Tuition)', 230000, 80000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kalema Abdulrahim Abubakim', 'Middle Class', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kato James', 'Middle Class', 'School Fees (Tuition)', 230000, 0, 'Cash', 'Nalukenge Jane', 'Full payment', 'bursar'),
  (v_tenant_id, 'Kassina John', 'Middle Class', 'School Fees (Tuition)', 230000, 0, 'Cash', 'Nalukenge Jane', 'Full payment', 'bursar'),
  (v_tenant_id, 'Namayanja Joweria', 'Middle Class', 'School Fees (Tuition)', 280000, 170000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kayemba Ronnie', 'Middle Class', 'School Fees (Tuition)', 300000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Beesa Imran', 'Middle Class', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mercy', 'Middle Class', 'School Fees (Tuition)', 200000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mercy Biira', 'Middle Class', 'School Fees (Tuition)', 200000, 50000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kyakuna Arthur', 'Middle Class', 'School Fees (Tuition)', 200000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kimbugwe Fatham', 'Middle Class', 'School Fees (Tuition)', 260000, 260000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mwanje Ranwah', 'Middle Class', 'School Fees (Tuition)', 200000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mutumba Hayan', 'Middle Class', 'School Fees (Tuition)', 270000, 120000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ndinayo Elijah', 'Middle Class', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Simoka Aaron', 'Middle Class', 'School Fees (Tuition)', 100000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mawanda Tanish', 'Top Class', 'School Fees (Tuition)', 290000, 290000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Namuyanja Sarah', 'Top Class', 'School Fees (Tuition)', 260000, 160000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mutebi Parvin', 'Top Class', 'School Fees (Tuition)', 260000, 260000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Babirye Daniella', 'Top Class', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kato Dan', 'Top Class', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Malaika Natalia', 'Top Class', 'School Fees (Tuition)', 300000, 40000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kato Kirumira', 'Top Class', 'School Fees (Tuition)', 150000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kasswa Emma', 'Top Class', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mokungi Nicole', 'Top Class', 'School Fees (Tuition)', 260000, 260000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Asiimwe Timothy', 'Top Class', 'School Fees (Tuition)', 480000, 90000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nagaba Dellah', 'Top Class', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Bahati Rania', 'Top Class', 'School Fees (Tuition)', 280000, 0, 'Cash', 'Nalukenge Jane', 'Full payment', 'bursar'),
  (v_tenant_id, 'Twebaze Isaaya', 'Top Class', 'School Fees (Tuition)', 230000, 30000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Namukwaya Daniella', 'Top Class', 'School Fees (Tuition)', 230000, 130000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakanwoki Emarine', 'Top Class', 'School Fees (Tuition)', 280000, 210000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nansuyimba Martina', 'Primary Two', 'School Fees (Tuition)', 420000, 170000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nalukenge Patricia', 'Primary Two', 'School Fees (Tuition)', 280000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Abaho Arthur', 'Primary Two', 'School Fees (Tuition)', 280000, 80000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakato Rashidah', 'Primary Two', 'School Fees (Tuition)', 890000, 690000, 'Cash', 'Nalukenge Jane', 'Includes arrears', 'bursar'),
  (v_tenant_id, 'Kasswa Rashid', 'Primary Two', 'School Fees (Tuition)', 890000, 890000, 'Cash', 'Nalukenge Jane', 'Includes arrears', 'bursar'),
  (v_tenant_id, 'Nbagide Mariam', 'Primary Two', 'School Fees (Tuition)', 240000, 140000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kalusimbi Teyin', 'Primary Two', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Namazzi Paris', 'Primary Two', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kimbowa Elijah', 'Primary Two', 'School Fees (Tuition)', 250000, 160000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kalungi Joylin', 'Primary Two', 'School Fees (Tuition)', 200000, 50000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kamooga Alton', 'Primary Two', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kawesa Jonah', 'Primary Two', 'School Fees (Tuition)', 450000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mulindo Martha', 'Primary Two', 'School Fees (Tuition)', 220000, 120000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kimera Imran', 'Primary Two', 'School Fees (Tuition)', 280000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Tujjeesa Erisabesi', 'Primary Two', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kirabo Sarah Nabaagala', 'Primary Two', 'School Fees (Tuition)', 200000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Tamale Hilal Nassor', 'Primary Two', 'School Fees (Tuition)', 370000, 170000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nafuna Patricia', 'Primary Two', 'School Fees (Tuition)', 350000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kakotio Payton', 'Primary Two', 'School Fees (Tuition)', 280000, 40000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssegazii Mathew', 'Primary Two', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nyanzi Calvin Kampala', 'Primary Two', 'School Fees (Tuition)', 180000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nachwa Ronah', 'Primary Three', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakimuli Queen Kevin', 'Primary Three', 'School Fees (Tuition)', 300000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Numbere Micheal', 'Primary Three', 'School Fees (Tuition)', 220000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakaboye Whitney', 'Primary Three', 'School Fees (Tuition)', 280000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kasuja Salmah', 'Primary Three', 'School Fees (Boarding)', 400000, 200000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Babirye Ronitah', 'Primary Three', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Lugoboli Charles', 'Primary Three', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Arinaitwe Jeremiah', 'Primary Three', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nkatia Jamila', 'Primary Three', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kemicisa Elizabeth', 'Primary Three', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakayenga Bushirah', 'Primary Three', 'School Fees (Tuition)', 280000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mulungi Sharifah', 'Primary Three', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Aizuka Trevor', 'Primary Three', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssebyesero Raymond', 'Primary Three', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Amanda Mikeiparah', 'Primary Three', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kamoga Adasa Esther', 'Primary Three', 'School Fees (Tuition)', 150000, 75000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mukisa Tania', 'Primary Three', 'School Fees (Boarding)', 500000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Ijungo Mathias', 'Primary Four', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Yiga Rashim', 'Primary Four', 'School Fees (Tuition)', 410000, 210000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kasswa David', 'Primary Four', 'School Fees (Tuition)', 500000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Asiimwe Brenda', 'Primary Four', 'School Fees (Tuition)', 500000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kimuli Marvin', 'Primary Four', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nantongo Hashimin Tara', 'Primary Four', 'School Fees (Tuition)', 400000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakato Annet Favour', 'Primary Five', 'School Fees (Boarding)', 500000, 200000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Nakalema Patricia', 'Primary Five', 'School Fees (Boarding)', 350000, 250000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Nakamoga Victoria', 'Primary Five', 'School Fees (Tuition)', 300000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssekyanzi Octavian', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakato Shabiba', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakimuli Maria Ketra', 'Primary Five', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Namntovu Jennifer', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakituba Anna', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mulindwa Jash', 'Primary Five', 'School Fees (Boarding)', 450000, 450000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Kitiibwa Shantel', 'Primary Five', 'School Fees (Boarding)', 400000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Nassuna Leticia', 'Primary Six', 'School Fees (Tuition)', 240000, 240000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssekabira Oscar', 'Primary Six', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Talibu Shubra', 'Primary Six', 'School Fees (Tuition)', 300000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nakiwa Joan', 'Primary Six', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssempijja Shammah', 'Primary Six', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nabukeera Margie', 'Primary Six', 'School Fees (Tuition)', 260000, 60000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ikanga Joyce', 'Primary Six', 'School Fees (Boarding)', 500000, 300000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Nakimbugwe Ketra', 'Primary Six', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Kanamwanji Malcolm', 'Primary Six', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nalugwa Sauya', 'Primary Six', 'School Fees (Tuition)', 230000, 70000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Mwanje Rayan', 'Primary Six', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Kamooga Emmanuel', 'Primary Six', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nanteza Keira Tendo', 'Primary Seven', 'School Fees (Tuition)', 500000, 120000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Sophie Bani Musa', 'Primary Seven', 'School Fees (Tuition)', 270000, 140000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Nampala Moureen', 'Primary Seven', 'School Fees (Tuition)', 350000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ssekidde Saifuh', 'Primary Seven', 'School Fees (Boarding)', 500000, 300000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Nabbumba Fann', 'Primary Seven', 'School Fees (Boarding)', 450000, 300000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Kamale Topister', 'Primary Seven', 'School Fees (Tuition)', 350000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
  (v_tenant_id, 'Ikanga Obadia', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Mpindi Ruth', 'Primary Seven', 'School Fees (Boarding)', 400000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Mpinda Danabell', 'Primary Seven', 'School Fees (Boarding)', 400000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Asiimwe Brendah', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Kabite Tranella', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Nakamoga Queen', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Mulindwa Josh', 'Primary Seven', 'School Fees (Boarding)', 450000, 450000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Waswa Joe', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
  (v_tenant_id, 'Sekiremba Jonah', 'Primary Seven', 'School Fees (Boarding)', 450000, 450000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar');

  RAISE NOTICE 'Imported fee records into Supabase for tenant %', v_tenant_id;
END $$;
