-- Import all Kabs Lily Fees and Student Accounts into Supabase
-- Run this in the Supabase SQL Editor

DELETE FROM school_income WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre';
DELETE FROM fees WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre';

INSERT INTO school_income (tenant_id, student_name, class, source_type, amount, unspent_balance, payment_method, received_by, notes, logged_by) VALUES
('kabs-lily-junior-school-and-kindercare-centre', 'Namala Leticia', 'Baby Class', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Arinaitwe Elijah', 'Baby Class', 'School Fees (Boarding)', 350000, 250000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssentongo Alpha', 'Baby Class', 'School Fees (Tuition)', 390000, 190000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Blessing Namusisi', 'Baby Class', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kisakye Jemimah', 'Baby Class', 'School Fees (Tuition)', 250000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Male David Joshua', 'Baby Class', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Lataya Elvis', 'Baby Class', 'School Fees (Tuition)', 200000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssuna Traylin', 'Baby Class', 'School Fees (Tuition)', 260000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Momoa Kent', 'Baby Class', 'School Fees (Tuition)', 250000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Eady Steven', 'Baby Class', 'School Fees (Tuition)', 280000, 130000, 'Cash', 'Nalukenge Jane', 'Paid in 3 installments', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nalubwama Maria Blessing', 'Baby Class', 'School Fees (Tuition)', 230000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kirabo Wisdom', 'Baby Class', 'School Fees (Tuition)', 235000, 125000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kirabo Terisa', 'Baby Class', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mucwanya Janiel', 'Baby Class', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nabbanya Miracle', 'Middle Class', 'School Fees (Tuition)', 155000, 65000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kiberu Rohan', 'Middle Class', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssenyondo Rayan', 'Middle Class', 'School Fees (Tuition)', 200000, 125000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kalungi Jovitah', 'Middle Class', 'School Fees (Tuition)', 200000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kemirembe Dorothy', 'Middle Class', 'School Fees (Tuition)', 200000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Namatovu Skylar', 'Middle Class', 'School Fees (Tuition)', 280000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Bagonza Isaiah', 'Middle Class', 'School Fees (Tuition)', 230000, 80000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kalema Abdulrahim Abubakim', 'Middle Class', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kato James', 'Middle Class', 'School Fees (Tuition)', 230000, 0, 'Cash', 'Nalukenge Jane', 'Full payment', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kassina John', 'Middle Class', 'School Fees (Tuition)', 230000, 0, 'Cash', 'Nalukenge Jane', 'Full payment', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Namayanja Joweria', 'Middle Class', 'School Fees (Tuition)', 280000, 170000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kayemba Ronnie', 'Middle Class', 'School Fees (Tuition)', 300000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Beesa Imran', 'Middle Class', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mercy', 'Middle Class', 'School Fees (Tuition)', 200000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mercy Biira', 'Middle Class', 'School Fees (Tuition)', 200000, 50000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kyakuna Arthur', 'Middle Class', 'School Fees (Tuition)', 200000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kimbugwe Fatham', 'Middle Class', 'School Fees (Tuition)', 260000, 260000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mwanje Ranwah', 'Middle Class', 'School Fees (Tuition)', 200000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mutumba Hayan', 'Middle Class', 'School Fees (Tuition)', 270000, 120000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ndinayo Elijah', 'Middle Class', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Simoka Aaron', 'Middle Class', 'School Fees (Tuition)', 100000, 100000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mawanda Tanish', 'Top Class', 'School Fees (Tuition)', 290000, 290000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Namuyanja Sarah', 'Top Class', 'School Fees (Tuition)', 260000, 160000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mutebi Parvin', 'Top Class', 'School Fees (Tuition)', 260000, 260000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Babirye Daniella', 'Top Class', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kato Dan', 'Top Class', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Malaika Natalia', 'Top Class', 'School Fees (Tuition)', 300000, 40000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kato Kirumira', 'Top Class', 'School Fees (Tuition)', 150000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kasswa Emma', 'Top Class', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mokungi Nicole', 'Top Class', 'School Fees (Tuition)', 260000, 260000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Asiimwe Timothy', 'Top Class', 'School Fees (Tuition)', 480000, 90000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nagaba Dellah', 'Top Class', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Bahati Rania', 'Top Class', 'School Fees (Tuition)', 280000, 0, 'Cash', 'Nalukenge Jane', 'Full payment', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Twebaze Isaaya', 'Top Class', 'School Fees (Tuition)', 230000, 30000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Namukwaya Daniella', 'Top Class', 'School Fees (Tuition)', 230000, 130000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakanwoki Emarine', 'Top Class', 'School Fees (Tuition)', 280000, 210000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nansuyimba Martina', 'Primary Two', 'School Fees (Tuition)', 420000, 170000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nalukenge Patricia', 'Primary Two', 'School Fees (Tuition)', 280000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Abaho Arthur', 'Primary Two', 'School Fees (Tuition)', 280000, 80000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakato Rashidah', 'Primary Two', 'School Fees (Tuition)', 890000, 690000, 'Cash', 'Nalukenge Jane', 'Includes arrears', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kasswa Rashid', 'Primary Two', 'School Fees (Tuition)', 890000, 890000, 'Cash', 'Nalukenge Jane', 'Includes arrears', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nbagide Mariam', 'Primary Two', 'School Fees (Tuition)', 240000, 140000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kalusimbi Teyin', 'Primary Two', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Namazzi Paris', 'Primary Two', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kimbowa Elijah', 'Primary Two', 'School Fees (Tuition)', 250000, 160000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kalungi Joylin', 'Primary Two', 'School Fees (Tuition)', 200000, 50000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kamooga Alton', 'Primary Two', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kawesa Jonah', 'Primary Two', 'School Fees (Tuition)', 450000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mulindo Martha', 'Primary Two', 'School Fees (Tuition)', 220000, 120000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kimera Imran', 'Primary Two', 'School Fees (Tuition)', 280000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Tujjeesa Erisabesi', 'Primary Two', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kirabo Sarah Nabaagala', 'Primary Two', 'School Fees (Tuition)', 200000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Tamale Hilal Nassor', 'Primary Two', 'School Fees (Tuition)', 370000, 170000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nafuna Patricia', 'Primary Two', 'School Fees (Tuition)', 350000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kakotio Payton', 'Primary Two', 'School Fees (Tuition)', 280000, 40000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssegazii Mathew', 'Primary Two', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nyanzi Calvin Kampala', 'Primary Two', 'School Fees (Tuition)', 180000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nachwa Ronah', 'Primary Three', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakimuli Queen Kevin', 'Primary Three', 'School Fees (Tuition)', 300000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Numbere Micheal', 'Primary Three', 'School Fees (Tuition)', 220000, 220000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakaboye Whitney', 'Primary Three', 'School Fees (Tuition)', 280000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kasuja Salmah', 'Primary Three', 'School Fees (Boarding)', 400000, 200000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Babirye Ronitah', 'Primary Three', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Lugoboli Charles', 'Primary Three', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Arinaitwe Jeremiah', 'Primary Three', 'School Fees (Tuition)', 280000, 180000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nkatia Jamila', 'Primary Three', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kemicisa Elizabeth', 'Primary Three', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakayenga Bushirah', 'Primary Three', 'School Fees (Tuition)', 280000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mulungi Sharifah', 'Primary Three', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Aizuka Trevor', 'Primary Three', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssebyesero Raymond', 'Primary Three', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Amanda Mikeiparah', 'Primary Three', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kamoga Adasa Esther', 'Primary Three', 'School Fees (Tuition)', 150000, 75000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mukisa Tania', 'Primary Three', 'School Fees (Boarding)', 500000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ijungo Mathias', 'Primary Four', 'School Fees (Tuition)', 250000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Yiga Rashim', 'Primary Four', 'School Fees (Tuition)', 410000, 210000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kasswa David', 'Primary Four', 'School Fees (Tuition)', 500000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Asiimwe Brenda', 'Primary Four', 'School Fees (Tuition)', 500000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kimuli Marvin', 'Primary Four', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nantongo Hashimin Tara', 'Primary Four', 'School Fees (Tuition)', 400000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakato Annet Favour', 'Primary Five', 'School Fees (Boarding)', 500000, 200000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakalema Patricia', 'Primary Five', 'School Fees (Boarding)', 350000, 250000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakamoga Victoria', 'Primary Five', 'School Fees (Tuition)', 300000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssekyanzi Octavian', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakato Shabiba', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakimuli Maria Ketra', 'Primary Five', 'School Fees (Tuition)', 280000, 280000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Namntovu Jennifer', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakituba Anna', 'Primary Five', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mulindwa Jash', 'Primary Five', 'School Fees (Boarding)', 450000, 450000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kitiibwa Shantel', 'Primary Five', 'School Fees (Boarding)', 400000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nassuna Leticia', 'Primary Six', 'School Fees (Tuition)', 240000, 240000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssekabira Oscar', 'Primary Six', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Talibu Shubra', 'Primary Six', 'School Fees (Tuition)', 300000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakiwa Joan', 'Primary Six', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssempijja Shammah', 'Primary Six', 'School Fees (Tuition)', 300000, 300000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nabukeera Margie', 'Primary Six', 'School Fees (Tuition)', 260000, 60000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ikanga Joyce', 'Primary Six', 'School Fees (Boarding)', 500000, 300000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakimbugwe Ketra', 'Primary Six', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kanamwanji Malcolm', 'Primary Six', 'School Fees (Tuition)', 250000, 250000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nalugwa Sauya', 'Primary Six', 'School Fees (Tuition)', 230000, 70000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mwanje Rayan', 'Primary Six', 'School Fees (Tuition)', 230000, 230000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kamooga Emmanuel', 'Primary Six', 'School Fees (Tuition)', 150000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nanteza Keira Tendo', 'Primary Seven', 'School Fees (Tuition)', 500000, 120000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Sophie Bani Musa', 'Primary Seven', 'School Fees (Tuition)', 270000, 140000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nampala Moureen', 'Primary Seven', 'School Fees (Tuition)', 350000, 150000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ssekidde Saifuh', 'Primary Seven', 'School Fees (Boarding)', 500000, 300000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nabbumba Fann', 'Primary Seven', 'School Fees (Boarding)', 450000, 300000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kamale Topister', 'Primary Seven', 'School Fees (Tuition)', 350000, 200000, 'Cash', 'Nalukenge Jane', '', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Ikanga Obadia', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mpindi Ruth', 'Primary Seven', 'School Fees (Boarding)', 400000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mpinda Danabell', 'Primary Seven', 'School Fees (Boarding)', 400000, 400000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Asiimwe Brendah', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Kabite Tranella', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Nakamoga Queen', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Mulindwa Josh', 'Primary Seven', 'School Fees (Boarding)', 450000, 450000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Waswa Joe', 'Primary Seven', 'School Fees (Boarding)', 500000, 500000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar'),
('kabs-lily-junior-school-and-kindercare-centre', 'Sekiremba Jonah', 'Primary Seven', 'School Fees (Boarding)', 450000, 450000, 'Cash', 'Nalukenge Jane', 'Boarding student', 'bursar');
