-- Sentinel telemetry, part 2: Database Webhooks for failed writes.
--
-- The frontend already POSTs uncaught render crashes to the Sentinel
-- worker's /telemetry endpoint (see the GlobalErrorBoundary in
-- NEXT OS.html and peak-primary/index.html). This adds the other half:
-- a durable log of *failed Supabase writes* (e.g. a CSV import batch that
-- got rejected), fed to the same worker via a Database Webhook so Sentinel
-- can see failures even when nobody has the tab open at the time.
--
-- Run this once in the Supabase SQL editor.

CREATE TABLE IF NOT EXISTS sync_errors (
  id          bigint generated by default as identity primary key,
  tenant_id   text,
  source      text NOT NULL,        -- e.g. 'csv_import_students', 'csv_import_fees'
  operation   text NOT NULL,        -- 'insert' | 'update' | 'delete'
  table_name  text,
  message     text NOT NULL,
  detail      jsonb DEFAULT '{}',
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE sync_errors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public write" ON sync_errors;
DROP POLICY IF EXISTS "Public read" ON sync_errors;
CREATE POLICY "Public write" ON sync_errors FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read" ON sync_errors FOR SELECT USING (true);

-- ─────────────────────────────────────────────────────────────────────────
-- Wire this table to the Sentinel worker as a Database Webhook:
--
--   Supabase Dashboard → Database → Webhooks → Create a new webhook
--     Table:      sync_errors
--     Events:     INSERT
--     Type:       HTTP Request
--     Method:     POST
--     URL:        https://nextos-sentinel.<your-subdomain>.workers.dev/webhook/db-error
--     Headers:    Content-Type: application/json
--
-- Supabase will POST the new row (as { type: 'INSERT', table: 'sync_errors',
-- record: {...} }) to that route. See handleDbErrorWebhook in
-- sentinel-worker.js, which normalizes it into the same shape triggerSelfHealing
-- already expects and hands it off to the self-healing routine.
-- ─────────────────────────────────────────────────────────────────────────
