-- ============================================================================
-- KABSLILY: replace existing students/fees with the authoritative roster
-- SOURCE: KABS_Student_Register_All_Classes (1).docx (day scholars, 156 ledger
-- rows across 11 classes incl. "Class Not Yet Confirmed") + a separately
-- provided "Boarding Students and Their Fees" list (22 names), both dated
-- 2026-07-31. This supersedes supabase-kabslily-authoritative-reimport.sql's
-- earlier, partial version (that one used a shorter day-only list pasted
-- inline; this one is generated straight from the actual register document).
--
-- WHAT CHANGED vs the current Supabase data: the tenants/fleet fixes earlier
-- this week got KABSLILY visible again, but the underlying students/fees
-- data was a partial import (148 students, only 17 fee rows total). This
-- replaces it with 166 students (157 from the day register + 9 boarding-only
-- students not found in the day register) and their Term 2 2026 charges/
-- payments, with boarding students' fees corrected to the boarding rate.
--
-- BEFORE RUNNING: this permanently deletes every existing KABSLILY students
-- and fees row and replaces them with the set below. Export a copy from the
-- Supabase table editor first if you want a backup.
--
-- REVIEW THESE 30 ITEMS — some are the source ledger's own flagged
-- ambiguities (balance conflicts, unclear names), others are judgment calls
-- I made matching the boarding list against the day register by name
-- similarity. High-confidence matches (>=0.90 similarity, e.g. spelling
-- variants like "Asiimwe Brendah"/"Asiimwe Brenda") were applied directly.
-- Medium-confidence matches (e.g. "Mpindi Ruth" -> day-list's "Maindi Ruth",
-- which usefully fills in a day-list record that had NO fee data at all)
-- were applied but are flagged for verification. Anything below that
-- threshold was added as a new, separate boarding-only student rather than
-- risk merging two different children's financial records:
--   1. Aizuka Trevor appears in BOTH Primary Three and Primary Six with the identical fee (230,000) — very likely the same child recorded twice under the wrong class in the source ledger, not two different children. Both rows were kept (linked by name+class so nothing crossed over incorrectly) — please confirm which class is correct and delete the wrong one.
--   2. Arinaitwe Elijah (Baby Class): matched to boarding list entry 'Alinaitwe Elijah' — marked is_boarding=true, full fees corrected to boarding rate 350,000 (day-list fee was 250,000); kept the day-list's recorded payment amount.
--   3. Kato Kirumira (Top Class): full_fees 150000 - paid 80000 = 70000 but source balance says 220000 (220,000). Recorded payments as transcribed; conflict needs manual reconciliation.
--   4. Bahati Rania / Alkandi Muhammad (Top Class): source row lists two names sharing one fee figure (280000) — no fee rows created for either, needs manual split.
--   5. Amanya Aaron (Primary One): full_fees 250000 - paid 200000 = 50000 but source balance says 80000 (80,000). Recorded payments as transcribed; conflict needs manual reconciliation.
--   6. Ndagire Angel (Primary One): full_fees 250000 - paid 100000 = 150000 but source balance says 180000 (180,000). Recorded payments as transcribed; conflict needs manual reconciliation.
--   7. Amirah (Primary One): no fee figures in source — student created with no fee rows.
--   8. Nansuyimba Martina (Primary Two): full_fees 420000 - paid 250000 = 170000 but source balance says 60000 (260,000 / 60,000). Recorded payments as transcribed; conflict needs manual reconciliation.
--   9. Nakato Rashidah (Primary Two): full_fees 890000 - paid 200000 = 690000 but source balance says 580000 (680,000 / 580,000). Recorded payments as transcribed; conflict needs manual reconciliation.
--   10. Kasuja Salmah (Primary Three): matched to boarding list entry 'Kasujja Salmah' — marked is_boarding=true, full fees corrected to boarding rate 400,000 (day-list fee was 400,000); kept the day-list's recorded payment amount.
--   11. Babirye Ronitah (Primary Three): matched to boarding list entry 'Babirye Ronitah' — marked is_boarding=true, full fees corrected to boarding rate 500,000 (day-list fee was 500,000); kept the day-list's recorded payment amount.
--   12. Maindi Ruth (Primary Three): matched to boarding list entry 'Mpindi Ruth' — marked is_boarding=true, full fees corrected to boarding rate 400,000 (day-list fee was ); kept the day-list's recorded payment amount.
--   13. Mulindonda Joel (Primary Three): matched to boarding list entry 'Mulindwa Joel' — marked is_boarding=true, full fees corrected to boarding rate 450,000 (day-list fee was ); kept the day-list's recorded payment amount.
--   14. Mukisa Tania (Primary Three): matched to boarding list entry 'Mukisa Tania' — marked is_boarding=true, full fees corrected to boarding rate 500,000 (day-list fee was 500,000); kept the day-list's recorded payment amount.
--   15. Asiimwe Brenda (Primary Four): matched to boarding list entry 'Asiimwe Brendah' — marked is_boarding=true, full fees corrected to boarding rate 500,000 (day-list fee was 500,000); kept the day-list's recorded payment amount.
--   16. Nakato Annet Favour (Primary Five): matched to boarding list entry 'Nakato Annet Favour' — marked is_boarding=true, full fees corrected to boarding rate 500,000 (day-list fee was 500,000); kept the day-list's recorded payment amount.
--   17. Mulindwa Jash (Primary Five): matched to boarding list entry 'Mulindwa Josh' — marked is_boarding=true, full fees corrected to boarding rate 450,000 (day-list fee was 450,000); kept the day-list's recorded payment amount.
--   18. Kitiibwa Shantel (Primary Five): matched to boarding list entry 'Kitibwa Shantel' — marked is_boarding=true, full fees corrected to boarding rate 400,000 (day-list fee was 400,000); kept the day-list's recorded payment amount.
--   19. Ssekabira Oscar (Primary Six): matched to boarding list entry 'Sekabira Oscar' — marked is_boarding=true, full fees corrected to boarding rate 500,000 (day-list fee was 500,000); kept the day-list's recorded payment amount.
--   20. Ikanga Joyce (Primary Six): matched to boarding list entry 'Ikanga Joyce' — marked is_boarding=true, full fees corrected to boarding rate 500,000 (day-list fee was 500,000); kept the day-list's recorded payment amount.
--   21. Nakamoga Queen Florence (Class Not Yet Confirmed): matched to boarding list entry 'Nakamaga Queen' — marked is_boarding=true, full fees corrected to boarding rate 500,000 (day-list fee was 350,000); kept the day-list's recorded payment amount.
--   22. Mulungi Patricia: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 350,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   23. Ikanga Obadia: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 500,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   24. Mpinda Danabell: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 400,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   25. Panteza Ketra: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 500,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   26. Kabite Tranella: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 500,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   27. Nabumba Ednar: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 450,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   28. Waswa Jev: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 500,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   29. Sekiremba Jonah: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 450,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
--   30. Sekitto Saifu: on the boarding list but no confident match in the day-scholar register — added as a new boarding student (stream 'Class Not Yet Confirmed', fee 500,000), no payment recorded (none given). Please confirm class + check for a possible existing duplicate.
-- ============================================================================

BEGIN;

DELETE FROM fees WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre';
DELETE FROM students WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre';

WITH new_students AS (
  INSERT INTO students (tenant_id, name, stream, guardian_name, status, is_boarding)
  VALUES
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namala Leticia', 'Baby Class', 'Parent of Namala Leticia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Arinaitwe Elijah', 'Baby Class', 'Parent of Arinaitwe Elijah', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssentongo Alpha', 'Baby Class', 'Parent of Ssentongo Alpha', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Blessing Namusisi', 'Baby Class', 'Parent of Blessing Namusisi', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kisakye Jemimah', 'Baby Class', 'Parent of Kisakye Jemimah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Male David Joshua', 'Baby Class', 'Parent of Male David Joshua', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Lataya Elvis', 'Baby Class', 'Parent of Lataya Elvis', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssuna Traylin', 'Baby Class', 'Parent of Ssuna Traylin', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Momoa Kent', 'Baby Class', 'Parent of Momoa Kent', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Eady Steven', 'Baby Class', 'Parent of Eady Steven', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nalubwama Maria Blessing', 'Baby Class', 'Parent of Nalubwama Maria Blessing', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kirabo Wisdom', 'Baby Class', 'Parent of Kirabo Wisdom', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kirabo Terisa', 'Baby Class', 'Parent of Kirabo Terisa', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mucwanya Janiel', 'Baby Class', 'Parent of Mucwanya Janiel', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nabbanya Miracle', 'Middle Class', 'Parent of Nabbanya Miracle', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kiberu Rohan', 'Middle Class', 'Parent of Kiberu Rohan', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssenyondo Rayan', 'Middle Class', 'Parent of Ssenyondo Rayan', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kalungi Jovitah', 'Middle Class', 'Parent of Kalungi Jovitah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kemirembe Dorothy', 'Middle Class', 'Parent of Kemirembe Dorothy', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namatovu Skylar', 'Middle Class', 'Parent of Namatovu Skylar', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Bagonza Isaiah', 'Middle Class', 'Parent of Bagonza Isaiah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kalema Abdulrahim Abubakim', 'Middle Class', 'Parent of Kalema Abdulrahim Abubakim', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kato James', 'Middle Class', 'Parent of Kato James', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kassina John', 'Middle Class', 'Parent of Kassina John', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namayanja Joweria', 'Middle Class', 'Parent of Namayanja Joweria', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kayemba Ronnie', 'Middle Class', 'Parent of Kayemba Ronnie', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Beesa Imran', 'Middle Class', 'Parent of Beesa Imran', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mercy', 'Middle Class', 'Parent of Mercy', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mercy Biira', 'Middle Class', 'Parent of Mercy Biira', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kyakuna Arthur', 'Middle Class', 'Parent of Kyakuna Arthur', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kimbugwe Fatham', 'Middle Class', 'Parent of Kimbugwe Fatham', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mwanje Ranwah', 'Middle Class', 'Parent of Mwanje Ranwah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mutumba Hayan', 'Middle Class', 'Parent of Mutumba Hayan', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ndinayo Elijah', 'Middle Class', 'Parent of Ndinayo Elijah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Simoka Aaron', 'Middle Class', 'Parent of Simoka Aaron', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mawanda Tanish', 'Top Class', 'Parent of Mawanda Tanish', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namuyanja Sarah', 'Top Class', 'Parent of Namuyanja Sarah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mutebi Parvin', 'Top Class', 'Parent of Mutebi Parvin', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Babirye Daniella', 'Top Class', 'Parent of Babirye Daniella', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kato Dan', 'Top Class', 'Parent of Kato Dan', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Malaika Natalia', 'Top Class', 'Parent of Malaika Natalia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kato Kirumira', 'Top Class', 'Parent of Kato Kirumira', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kasswa Emma', 'Top Class', 'Parent of Kasswa Emma', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mokungi Nicole', 'Top Class', 'Parent of Mokungi Nicole', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Asiimwe Timothy', 'Top Class', 'Parent of Asiimwe Timothy', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nagaba Dellah', 'Top Class', 'Parent of Nagaba Dellah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Bahati Rania', 'Top Class', 'Parent of Bahati Rania', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Alkandi Muhammad', 'Top Class', 'Parent of Alkandi Muhammad', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Twebaze Isaaya', 'Top Class', 'Parent of Twebaze Isaaya', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namukwaya Daniella', 'Top Class', 'Parent of Namukwaya Daniella', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakanwoki Emarine', 'Top Class', 'Parent of Nakanwoki Emarine', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nyanzi Jeriden', 'Primary One', 'Parent of Nyanzi Jeriden', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namuli Ashley Peace', 'Primary One', 'Parent of Namuli Ashley Peace', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakimuli Maluwah', 'Primary One', 'Parent of Nakimuli Maluwah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kigozi Melvin', 'Primary One', 'Parent of Kigozi Melvin', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nalumansi Tryphena', 'Primary One', 'Parent of Nalumansi Tryphena', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Amanya Aaron', 'Primary One', 'Parent of Amanya Aaron', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Tamale Roger', 'Primary One', 'Parent of Tamale Roger', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kwagalakwe Bseza', 'Primary One', 'Parent of Kwagalakwe Bseza', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namuwoonge Martha', 'Primary One', 'Parent of Namuwoonge Martha', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Alupo Brenda', 'Primary One', 'Parent of Alupo Brenda', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Muwanguzi Erisa', 'Primary One', 'Parent of Muwanguzi Erisa', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mukasa Elijah', 'Primary One', 'Parent of Mukasa Elijah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ndagire Angel', 'Primary One', 'Parent of Ndagire Angel', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Obadia Kirangos', 'Primary One', 'Parent of Obadia Kirangos', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namyenya Jaselyn', 'Primary One', 'Parent of Namyenya Jaselyn', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Luwalde Keren', 'Primary One', 'Parent of Luwalde Keren', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mehek Jot', 'Primary One', 'Parent of Mehek Jot', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namberya Patricia', 'Primary One', 'Parent of Namberya Patricia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kyambade Ernest', 'Primary One', 'Parent of Kyambade Ernest', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nsobya Praise', 'Primary One', 'Parent of Nsobya Praise', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Amirah', 'Primary One', 'Parent of Amirah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Harriet', 'Primary One', 'Parent of Harriet', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Flavia', 'Primary One', 'Parent of Flavia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nansuyimba Martina', 'Primary Two', 'Parent of Nansuyimba Martina', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nalukenge Patricia', 'Primary Two', 'Parent of Nalukenge Patricia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Abaho Arthur', 'Primary Two', 'Parent of Abaho Arthur', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakato Rashidah', 'Primary Two', 'Parent of Nakato Rashidah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kasswa Rashid', 'Primary Two', 'Parent of Kasswa Rashid', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nbagide Mariam', 'Primary Two', 'Parent of Nbagide Mariam', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kalusimbi Teyin', 'Primary Two', 'Parent of Kalusimbi Teyin', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namazzi Paris', 'Primary Two', 'Parent of Namazzi Paris', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kimbowa Elijah', 'Primary Two', 'Parent of Kimbowa Elijah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kalungi Joylin', 'Primary Two', 'Parent of Kalungi Joylin', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kamooga Alton', 'Primary Two', 'Parent of Kamooga Alton', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kawesa Jonah', 'Primary Two', 'Parent of Kawesa Jonah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mulindo Martha', 'Primary Two', 'Parent of Mulindo Martha', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kimera Imran', 'Primary Two', 'Parent of Kimera Imran', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Tujjeesa Erisabesi', 'Primary Two', 'Parent of Tujjeesa Erisabesi', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kirabo Sarah Nabaagala', 'Primary Two', 'Parent of Kirabo Sarah Nabaagala', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Tamale Hilal Nassor', 'Primary Two', 'Parent of Tamale Hilal Nassor', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nafuna Patricia', 'Primary Two', 'Parent of Nafuna Patricia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kakotio Payton', 'Primary Two', 'Parent of Kakotio Payton', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssegazii Mathew', 'Primary Two', 'Parent of Ssegazii Mathew', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nyanzi Calvin Kampala', 'Primary Two', 'Parent of Nyanzi Calvin Kampala', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nachwa Ronah', 'Primary Three', 'Parent of Nachwa Ronah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakimuli Queen Kevin', 'Primary Three', 'Parent of Nakimuli Queen Kevin', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Numbere Micheal', 'Primary Three', 'Parent of Numbere Micheal', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakaboye Whitney', 'Primary Three', 'Parent of Nakaboye Whitney', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kasuja Salmah', 'Primary Three', 'Parent of Kasuja Salmah', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Babirye Ronitah', 'Primary Three', 'Parent of Babirye Ronitah', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Lugoboli Charles', 'Primary Three', 'Parent of Lugoboli Charles', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Arinaitwe Jeremiah', 'Primary Three', 'Parent of Arinaitwe Jeremiah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nkatia Jamila', 'Primary Three', 'Parent of Nkatia Jamila', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kemicisa Elizabeth', 'Primary Three', 'Parent of Kemicisa Elizabeth', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakayenga Bushirah', 'Primary Three', 'Parent of Nakayenga Bushirah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mulungi Sharifah', 'Primary Three', 'Parent of Mulungi Sharifah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Aizuka Trevor', 'Primary Three', 'Parent of Aizuka Trevor', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssebyesero Raymond', 'Primary Three', 'Parent of Ssebyesero Raymond', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Amanda Mikeiparah', 'Primary Three', 'Parent of Amanda Mikeiparah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kamoga Adasa Esther', 'Primary Three', 'Parent of Kamoga Adasa Esther', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Maindi Ruth', 'Primary Three', 'Parent of Maindi Ruth', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mulindonda Joel', 'Primary Three', 'Parent of Mulindonda Joel', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mukisa Tania', 'Primary Three', 'Parent of Mukisa Tania', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ijungo Mathias', 'Primary Four', 'Parent of Ijungo Mathias', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Yiga Rashim', 'Primary Four', 'Parent of Yiga Rashim', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kasswa David', 'Primary Four', 'Parent of Kasswa David', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Asiimwe Brenda', 'Primary Four', 'Parent of Asiimwe Brenda', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kimuli Marvin', 'Primary Four', 'Parent of Kimuli Marvin', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nantongo Hashimin Tara', 'Primary Four', 'Parent of Nantongo Hashimin Tara', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakato Annet Favour', 'Primary Five', 'Parent of Nakato Annet Favour', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakalema Patricia', 'Primary Five', 'Parent of Nakalema Patricia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakamoga Victoria', 'Primary Five', 'Parent of Nakamoga Victoria', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssekyanzi Octavian', 'Primary Five', 'Parent of Ssekyanzi Octavian', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakato Shabiba', 'Primary Five', 'Parent of Nakato Shabiba', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakimuli Maria Ketra', 'Primary Five', 'Parent of Nakimuli Maria Ketra', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namntovu Jennifer', 'Primary Five', 'Parent of Namntovu Jennifer', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakituba Anna', 'Primary Five', 'Parent of Nakituba Anna', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mulindwa Jash', 'Primary Five', 'Parent of Mulindwa Jash', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kitiibwa Shantel', 'Primary Five', 'Parent of Kitiibwa Shantel', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Namigadde Monidah', 'Primary Five', 'Parent of Namigadde Monidah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nassuna Leticia', 'Primary Six', 'Parent of Nassuna Leticia', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssekabira Oscar', 'Primary Six', 'Parent of Ssekabira Oscar', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Talibu Shubra', 'Primary Six', 'Parent of Talibu Shubra', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakiwa Joan', 'Primary Six', 'Parent of Nakiwa Joan', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssempijja Shammah', 'Primary Six', 'Parent of Ssempijja Shammah', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nabukeera Margie', 'Primary Six', 'Parent of Nabukeera Margie', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Aizuka Trevor', 'Primary Six', 'Parent of Aizuka Trevor', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ikanga Joyce', 'Primary Six', 'Parent of Ikanga Joyce', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakimbugwe Ketra', 'Primary Six', 'Parent of Nakimbugwe Ketra', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kanamwanji Malcolm', 'Primary Six', 'Parent of Kanamwanji Malcolm', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nalugwa Sauya', 'Primary Six', 'Parent of Nalugwa Sauya', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mwanje Rayan', 'Primary Six', 'Parent of Mwanje Rayan', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kamooga Emmanuel', 'Primary Six', 'Parent of Kamooga Emmanuel', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nanteza Keira Tendo', 'Primary Seven', 'Parent of Nanteza Keira Tendo', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Sophie Bani Musa', 'Primary Seven', 'Parent of Sophie Bani Musa', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nampala Moureen', 'Primary Seven', 'Parent of Nampala Moureen', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssekidde Saifuh', 'Primary Seven', 'Parent of Ssekidde Saifuh', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nabbumba Fann', 'Primary Seven', 'Parent of Nabbumba Fann', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kamale Topister', 'Primary Seven', 'Parent of Kamale Topister', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ssebukeere Joel', 'Class Not Yet Confirmed', 'Parent of Ssebukeere Joel', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakangu Merush Jeminath', 'Class Not Yet Confirmed', 'Parent of Nakangu Merush Jeminath', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nakamoga Queen Florence', 'Class Not Yet Confirmed', 'Parent of Nakamoga Queen Florence', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kabiite Maria Ngonde', 'Class Not Yet Confirmed', 'Parent of Kabiite Maria Ngonde', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Zinfaune Claire', 'Class Not Yet Confirmed', 'Parent of Zinfaune Claire', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kawule Ronnie', 'Class Not Yet Confirmed', 'Parent of Kawule Ronnie', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mariam', 'Class Not Yet Confirmed', 'Parent of Mariam', 'active', false),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mulungi Patricia', 'Class Not Yet Confirmed', 'Parent of Mulungi Patricia', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Ikanga Obadia', 'Class Not Yet Confirmed', 'Parent of Ikanga Obadia', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Mpinda Danabell', 'Class Not Yet Confirmed', 'Parent of Mpinda Danabell', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Panteza Ketra', 'Class Not Yet Confirmed', 'Parent of Panteza Ketra', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Kabite Tranella', 'Class Not Yet Confirmed', 'Parent of Kabite Tranella', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Nabumba Ednar', 'Class Not Yet Confirmed', 'Parent of Nabumba Ednar', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Waswa Jev', 'Class Not Yet Confirmed', 'Parent of Waswa Jev', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Sekiremba Jonah', 'Class Not Yet Confirmed', 'Parent of Sekiremba Jonah', 'active', true),
  ('kabs-lily-junior-school-and-kindercare-centre', 'Sekitto Saifu', 'Class Not Yet Confirmed', 'Parent of Sekitto Saifu', 'active', true)
  RETURNING id, name, stream
)
INSERT INTO fees (tenant_id, student_id, term, kind, amount, notes)
VALUES
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namala Leticia' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namala Leticia' LIMIT 1), 'Term 2 2026', 'payment', -250000, 'Source confirms balance Nil (fully paid).'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Arinaitwe Elijah' LIMIT 1), 'Term 2 2026', 'charge', 350000, 'Balance query – verify'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Arinaitwe Elijah' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Balance query – verify'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssentongo Alpha' LIMIT 1), 'Term 2 2026', 'charge', 390000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssentongo Alpha' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Blessing Namusisi' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Blessing Namusisi' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kisakye Jemimah' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kisakye Jemimah' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Male David Joshua' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Male David Joshua' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Lataya Elvis' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssuna Traylin' LIMIT 1), 'Term 2 2026', 'charge', 260000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssuna Traylin' LIMIT 1), 'Term 2 2026', 'payment', -40000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Momoa Kent' LIMIT 1), 'Term 2 2026', 'charge', 250000, 'First name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Momoa Kent' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'First name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Eady Steven' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Eady Steven' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Eady Steven' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Eady Steven' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nalubwama Maria Blessing' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nalubwama Maria Blessing' LIMIT 1), 'Term 2 2026', 'payment', -50000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kirabo Wisdom' LIMIT 1), 'Term 2 2026', 'charge', 235000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kirabo Wisdom' LIMIT 1), 'Term 2 2026', 'payment', -110000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kirabo Terisa' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mucwanya Janiel' LIMIT 1), 'Term 2 2026', 'charge', 230000, 'Name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nabbanya Miracle' LIMIT 1), 'Term 2 2026', 'charge', 155000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nabbanya Miracle' LIMIT 1), 'Term 2 2026', 'payment', -90000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kiberu Rohan' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssenyondo Rayan' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssenyondo Rayan' LIMIT 1), 'Term 2 2026', 'payment', -75000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kalungi Jovitah' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kalungi Jovitah' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kemirembe Dorothy' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kemirembe Dorothy' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namatovu Skylar' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namatovu Skylar' LIMIT 1), 'Term 2 2026', 'payment', -130000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Bagonza Isaiah' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Bagonza Isaiah' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kalema Abdulrahim Abubakim' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kato James' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kato James' LIMIT 1), 'Term 2 2026', 'payment', -230000, 'Source confirms balance Nil (fully paid).'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kassina John' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kassina John' LIMIT 1), 'Term 2 2026', 'payment', -230000, 'Source confirms balance Nil (fully paid).'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namayanja Joweria' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namayanja Joweria' LIMIT 1), 'Term 2 2026', 'payment', -110000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kayemba Ronnie' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kayemba Ronnie' LIMIT 1), 'Term 2 2026', 'payment', -80000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Beesa Imran' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Beesa Imran' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mercy' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mercy' LIMIT 1), 'Term 2 2026', 'payment', -50000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mercy Biira' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mercy Biira' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kyakuna Arthur' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kimbugwe Fatham' LIMIT 1), 'Term 2 2026', 'charge', 260000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mwanje Ranwah' LIMIT 1), 'Term 2 2026', 'charge', 200000, 'Name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mwanje Ranwah' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mutumba Hayan' LIMIT 1), 'Term 2 2026', 'charge', 270000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mutumba Hayan' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mutumba Hayan' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ndinayo Elijah' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Simoka Aaron' LIMIT 1), 'Term 2 2026', 'charge', 100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mawanda Tanish' LIMIT 1), 'Term 2 2026', 'charge', 290000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuyanja Sarah' LIMIT 1), 'Term 2 2026', 'charge', 260000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuyanja Sarah' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mutebi Parvin' LIMIT 1), 'Term 2 2026', 'charge', 260000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Babirye Daniella' LIMIT 1), 'Term 2 2026', 'charge', 150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kato Dan' LIMIT 1), 'Term 2 2026', 'charge', 150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Malaika Natalia' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Malaika Natalia' LIMIT 1), 'Term 2 2026', 'payment', -260000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kato Kirumira' LIMIT 1), 'Term 2 2026', 'charge', 150000, 'Balance query – verify'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kato Kirumira' LIMIT 1), 'Term 2 2026', 'payment', -80000, 'Balance query – verify'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kasswa Emma' LIMIT 1), 'Term 2 2026', 'charge', 150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mokungi Nicole' LIMIT 1), 'Term 2 2026', 'charge', 260000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Asiimwe Timothy' LIMIT 1), 'Term 2 2026', 'charge', 480000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Asiimwe Timothy' LIMIT 1), 'Term 2 2026', 'payment', -390000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nagaba Dellah' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Twebaze Isaaya' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Twebaze Isaaya' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namukwaya Daniella' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namukwaya Daniella' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakanwoki Emarine' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakanwoki Emarine' LIMIT 1), 'Term 2 2026', 'payment', -70000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nyanzi Jeriden' LIMIT 1), 'Term 2 2026', 'charge', 210000, 'Fully paid'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nyanzi Jeriden' LIMIT 1), 'Term 2 2026', 'payment', -210000, 'Source confirms balance Nil (fully paid).'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuli Ashley Peace' LIMIT 1), 'Term 2 2026', 'charge', 390000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuli Ashley Peace' LIMIT 1), 'Term 2 2026', 'payment', -150000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuli Ashley Peace' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuli Ashley Peace' LIMIT 1), 'Term 2 2026', 'payment', -110000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakimuli Maluwah' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakimuli Maluwah' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kigozi Melvin' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kigozi Melvin' LIMIT 1), 'Term 2 2026', 'payment', -50000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nalumansi Tryphena' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Amanya Aaron' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Amanya Aaron' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Tamale Roger' LIMIT 1), 'Term 2 2026', 'charge', 300000, 'Three lines; fully paid'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Tamale Roger' LIMIT 1), 'Term 2 2026', 'payment', -300000, 'Source confirms balance Nil (fully paid) — recorded as one full payment; original source showed multiple partial lines: 140,000 / 100,000'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kwagalakwe Bseza' LIMIT 1), 'Term 2 2026', 'charge', 260000, 'Four payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kwagalakwe Bseza' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Four payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kwagalakwe Bseza' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Four payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kwagalakwe Bseza' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Four payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kwagalakwe Bseza' LIMIT 1), 'Term 2 2026', 'payment', -80000, 'Four payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuwoonge Martha' LIMIT 1), 'Term 2 2026', 'charge', 250000, 'Fully paid'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namuwoonge Martha' LIMIT 1), 'Term 2 2026', 'payment', -250000, 'Source confirms balance Nil (fully paid).'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Alupo Brenda' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Two lines; Δ30,000 noted'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Alupo Brenda' LIMIT 1), 'Term 2 2026', 'payment', -150000, 'Two lines; Δ30,000 noted'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Alupo Brenda' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two lines; Δ30,000 noted'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Muwanguzi Erisa' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Muwanguzi Erisa' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Muwanguzi Erisa' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mukasa Elijah' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Fully paid'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mukasa Elijah' LIMIT 1), 'Term 2 2026', 'payment', -280000, 'Source confirms balance Nil (fully paid).'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ndagire Angel' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ndagire Angel' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Obadia Kirangos' LIMIT 1), 'Term 2 2026', 'charge', 500000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Obadia Kirangos' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namyenya Jaselyn' LIMIT 1), 'Term 2 2026', 'charge', 170000, 'Fully paid'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namyenya Jaselyn' LIMIT 1), 'Term 2 2026', 'payment', -170000, 'Source confirms balance Nil (fully paid).'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Luwalde Keren' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Luwalde Keren' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mehek Jot' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mehek Jot' LIMIT 1), 'Term 2 2026', 'payment', -150000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mehek Jot' LIMIT 1), 'Term 2 2026', 'payment', -80000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namberya Patricia' LIMIT 1), 'Term 2 2026', 'charge', 260000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namberya Patricia' LIMIT 1), 'Term 2 2026', 'payment', -80000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namberya Patricia' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namberya Patricia' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Three payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kyambade Ernest' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kyambade Ernest' LIMIT 1), 'Term 2 2026', 'payment', -180000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nsobya Praise' LIMIT 1), 'Term 2 2026', 'charge', 180000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Harriet' LIMIT 1), 'Term 2 2026', 'charge', 200000, 'Surname not shown'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Flavia' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Flavia' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nansuyimba Martina' LIMIT 1), 'Term 2 2026', 'charge', 420000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nansuyimba Martina' LIMIT 1), 'Term 2 2026', 'payment', -150000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nansuyimba Martina' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nalukenge Patricia' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nalukenge Patricia' LIMIT 1), 'Term 2 2026', 'payment', -80000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Abaho Arthur' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Abaho Arthur' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakato Rashidah' LIMIT 1), 'Term 2 2026', 'charge', 890000, 'May include arrears'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakato Rashidah' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'May include arrears'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakato Rashidah' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'May include arrears'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kasswa Rashid' LIMIT 1), 'Term 2 2026', 'charge', 890000, '780,000 also noted'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nbagide Mariam' LIMIT 1), 'Term 2 2026', 'charge', 240000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nbagide Mariam' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kalusimbi Teyin' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Second name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namazzi Paris' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namazzi Paris' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kimbowa Elijah' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kimbowa Elijah' LIMIT 1), 'Term 2 2026', 'payment', -90000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kalungi Joylin' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kalungi Joylin' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kamooga Alton' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kamooga Alton' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kawesa Jonah' LIMIT 1), 'Term 2 2026', 'charge', 450000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kawesa Jonah' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kawesa Jonah' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mulindo Martha' LIMIT 1), 'Term 2 2026', 'charge', 220000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mulindo Martha' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kimera Imran' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kimera Imran' LIMIT 1), 'Term 2 2026', 'payment', -130000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Tujjeesa Erisabesi' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kirabo Sarah Nabaagala' LIMIT 1), 'Term 2 2026', 'charge', 200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kirabo Sarah Nabaagala' LIMIT 1), 'Term 2 2026', 'payment', -50000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Tamale Hilal Nassor' LIMIT 1), 'Term 2 2026', 'charge', 370000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Tamale Hilal Nassor' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nafuna Patricia' LIMIT 1), 'Term 2 2026', 'charge', 350000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nafuna Patricia' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kakotio Payton' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kakotio Payton' LIMIT 1), 'Term 2 2026', 'payment', -240000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssegazii Mathew' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nyanzi Calvin Kampala' LIMIT 1), 'Term 2 2026', 'charge', 180000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nachwa Ronah' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nachwa Ronah' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakimuli Queen Kevin' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakimuli Queen Kevin' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Numbere Micheal' LIMIT 1), 'Term 2 2026', 'charge', 220000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakaboye Whitney' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakaboye Whitney' LIMIT 1), 'Term 2 2026', 'payment', -80000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kasuja Salmah' LIMIT 1), 'Term 2 2026', 'charge', 400000, 'Boarding fee corrected from day-list (400,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kasuja Salmah' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Babirye Ronitah' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding fee corrected from day-list (500,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Lugoboli Charles' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Lugoboli Charles' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Arinaitwe Jeremiah' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Arinaitwe Jeremiah' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nkatia Jamila' LIMIT 1), 'Term 2 2026', 'charge', 250000, 'First name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nkatia Jamila' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'First name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kemicisa Elizabeth' LIMIT 1), 'Term 2 2026', 'charge', 250000, 'Marked ''out'' in source'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakayenga Bushirah' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakayenga Bushirah' LIMIT 1), 'Term 2 2026', 'payment', -130000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mulungi Sharifah' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Aizuka Trevor' AND stream = 'Primary Three' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssebyesero Raymond' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Amanda Mikeiparah' LIMIT 1), 'Term 2 2026', 'charge', 300000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kamoga Adasa Esther' LIMIT 1), 'Term 2 2026', 'charge', 150000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kamoga Adasa Esther' LIMIT 1), 'Term 2 2026', 'payment', -75000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Maindi Ruth' LIMIT 1), 'Term 2 2026', 'charge', 400000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mulindonda Joel' LIMIT 1), 'Term 2 2026', 'charge', 450000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mukisa Tania' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mukisa Tania' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Class inferred'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ijungo Mathias' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ijungo Mathias' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Yiga Rashim' LIMIT 1), 'Term 2 2026', 'charge', 410000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Yiga Rashim' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Yiga Rashim' LIMIT 1), 'Term 2 2026', 'payment', -100000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kasswa David' LIMIT 1), 'Term 2 2026', 'charge', 500000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kasswa David' LIMIT 1), 'Term 2 2026', 'payment', -300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Asiimwe Brenda' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding fee corrected from day-list (500,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Asiimwe Brenda' LIMIT 1), 'Term 2 2026', 'payment', -300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kimuli Marvin' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nantongo Hashimin Tara' LIMIT 1), 'Term 2 2026', 'charge', 400000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nantongo Hashimin Tara' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakato Annet Favour' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding fee corrected from day-list (500,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakato Annet Favour' LIMIT 1), 'Term 2 2026', 'payment', -300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakalema Patricia' LIMIT 1), 'Term 2 2026', 'charge', 240000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakalema Patricia' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakamoga Victoria' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakamoga Victoria' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssekyanzi Octavian' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakato Shabiba' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakimuli Maria Ketra' LIMIT 1), 'Term 2 2026', 'charge', 280000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namntovu Jennifer' LIMIT 1), 'Term 2 2026', 'charge', 300000, 'First name spelling unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakituba Anna' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mulindwa Jash' LIMIT 1), 'Term 2 2026', 'charge', 450000, 'Second name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kitiibwa Shantel' LIMIT 1), 'Term 2 2026', 'charge', 400000, 'Boarding fee corrected from day-list (400,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namigadde Monidah' LIMIT 1), 'Term 2 2026', 'charge', 350000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Namigadde Monidah' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nassuna Leticia' LIMIT 1), 'Term 2 2026', 'charge', 240000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssekabira Oscar' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding fee corrected from day-list (500,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Talibu Shubra' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Talibu Shubra' LIMIT 1), 'Term 2 2026', 'payment', -50000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakiwa Joan' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssempijja Shammah' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nabukeera Margie' LIMIT 1), 'Term 2 2026', 'charge', 260000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nabukeera Margie' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Aizuka Trevor' AND stream = 'Primary Six' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ikanga Joyce' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding fee corrected from day-list (500,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ikanga Joyce' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakimbugwe Ketra' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kanamwanji Malcolm' LIMIT 1), 'Term 2 2026', 'charge', 250000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nalugwa Sauya' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nalugwa Sauya' LIMIT 1), 'Term 2 2026', 'payment', -160000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mwanje Rayan' LIMIT 1), 'Term 2 2026', 'charge', 230000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kamooga Emmanuel' LIMIT 1), 'Term 2 2026', 'charge', 150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nanteza Keira Tendo' LIMIT 1), 'Term 2 2026', 'charge', 500000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nanteza Keira Tendo' LIMIT 1), 'Term 2 2026', 'payment', -380000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Sophie Bani Musa' LIMIT 1), 'Term 2 2026', 'charge', 270000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Sophie Bani Musa' LIMIT 1), 'Term 2 2026', 'payment', -50000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Sophie Bani Musa' LIMIT 1), 'Term 2 2026', 'payment', -80000, 'Two payment lines'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nampala Moureen' LIMIT 1), 'Term 2 2026', 'charge', 350000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nampala Moureen' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssekidde Saifuh' LIMIT 1), 'Term 2 2026', 'charge', 500000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssekidde Saifuh' LIMIT 1), 'Term 2 2026', 'payment', -200000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nabbumba Fann' LIMIT 1), 'Term 2 2026', 'charge', 450000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nabbumba Fann' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kamale Topister' LIMIT 1), 'Term 2 2026', 'charge', 350000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kamale Topister' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ssebukeere Joel' LIMIT 1), 'Term 2 2026', 'charge', 350000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakangu Merush Jeminath' LIMIT 1), 'Term 2 2026', 'charge', 350000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakangu Merush Jeminath' LIMIT 1), 'Term 2 2026', 'payment', -50000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakamoga Queen Florence' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding fee corrected from day-list (350,000)'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nakamoga Queen Florence' LIMIT 1), 'Term 2 2026', 'payment', -100000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kabiite Maria Ngonde' LIMIT 1), 'Term 2 2026', 'charge', 350000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kabiite Maria Ngonde' LIMIT 1), 'Term 2 2026', 'payment', -150000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Zinfaune Claire' LIMIT 1), 'Term 2 2026', 'charge', 350000, 'Name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Zinfaune Claire' LIMIT 1), 'Term 2 2026', 'payment', -120000, 'Name unclear'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kawule Ronnie' LIMIT 1), 'Term 2 2026', 'charge', 300000, NULL),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mariam' LIMIT 1), 'Term 2 2026', 'charge', 280000, 'Surname not shown'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mulungi Patricia' LIMIT 1), 'Term 2 2026', 'charge', 350000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Ikanga Obadia' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Mpinda Danabell' LIMIT 1), 'Term 2 2026', 'charge', 400000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Panteza Ketra' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Kabite Tranella' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Nabumba Ednar' LIMIT 1), 'Term 2 2026', 'charge', 450000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Waswa Jev' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Sekiremba Jonah' LIMIT 1), 'Term 2 2026', 'charge', 450000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.'),
  ('kabs-lily-junior-school-and-kindercare-centre', (SELECT id FROM new_students WHERE name = 'Sekitto Saifu' LIMIT 1), 'Term 2 2026', 'charge', 500000, 'Boarding-only entry — not found in day-scholar register, class unconfirmed.')
;

COMMIT;

-- Sanity checks after running:
-- SELECT count(*) FROM students WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre';                      -- expect 166
-- SELECT count(*) FROM students WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre' AND is_boarding;      -- expect 22
-- SELECT count(*) FROM fees WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre';
-- SELECT name, stream FROM students WHERE tenant_id = 'kabs-lily-junior-school-and-kindercare-centre' AND name = 'Aizuka Trevor'; -- the flagged duplicate, confirm/delete one
