import { listRows, saveRow, deleteRow } from '../data.js';
import { canDeleteOperations } from '../roles.js';
import { e, readableDate, empty, field, selectField, textArea, formActions, setBusy } from './records.js';
let selected=null;
const STATUS=[['held','Held'],['converted','Converted'],['released','Released'],['expired','Expired']];
function editor(row,identity){return `<form id="hold-form" class="record-form" data-id="${row?.id||''}"><div class="form-title span-2"><div><p class="eyebrow">${row?'DATE HOLD':'NEW DATE HOLD'}</p><h2>${row?e(row.contact_name):'Hold a date'}</h2></div></div>${field('contact_name','Contact name',row?.contact_name,{required:true})}${field('venue','Venue',row?.venue)}${field('starts_at','Starts',row?.starts_at?new Date(row.starts_at).toISOString().slice(0,16):'',{type:'datetime-local',required:true})}${field('ends_at','Ends',row?.ends_at?new Date(row.ends_at).toISOString().slice(0,16):'',{type:'datetime-local',required:true})}${field('expires_at','Hold expires',row?.expires_at?new Date(row.expires_at).toISOString().slice(0,16):'',{type:'datetime-local'})}${selectField('status','Status',row?.status||'held',STATUS)}${textArea('operational_notes','Operational notes',row?.operational_notes,'Do not put pricing or budget information here.')}${formActions(row?.id,canDeleteOperations(identity.role))}</form>`}
async function draw(context){const{client,identity,host}=context;host.innerHTML='<div class="module-loading">Loading date holds…</div>';try{const rows=await listRows(client,'date_holds','starts_at',true);const current=rows.find(x=>x.id===selected);host.innerHTML=`<div class="module-toolbar"><div><strong>${rows.filter(x=>x.status==='held').length} active holds</strong><span>Expiry is only used when you set it</span></div><button class="button primary" data-new>New date hold</button></div><div class="records-layout"><section class="record-list">${rows.length?rows.map(x=>`<button class="record-card${x.id===selected?' active':''}" data-row="${x.id}"><span><strong>${e(x.contact_name)}</strong><small>${e(readableDate(x.starts_at,true))}</small></span><em class="status">${e(x.status)}</em></button>`).join(''):empty('No dates are on hold.')}</section><section class="record-editor">${selected==='new'?editor(null,identity):current?editor(current,identity):'<div class="select-prompt"><h2>Select a date hold</h2><p>Open a hold to update its timing, status or notes.</p></div>'}</section></div>`;bind(context)}catch(error){host.innerHTML=`<div class="error-panel"><strong>Date holds could not be loaded.</strong><p>${e(error.message)}</p><button class="button secondary" data-retry>Try again</button></div>`;bind(context)}}
function bind(context){const{host,client,notify}=context;host.querySelector('[data-retry]')?.addEventListener('click',()=>draw(context));host.querySelector('[data-new]')?.addEventListener('click',()=>{selected='new';draw(context)});host.querySelectorAll('[data-row]').forEach(x=>x.addEventListener('click',()=>{selected=x.dataset.row;draw(context)}));host.querySelector('[data-cancel]')?.addEventListener('click',()=>{selected=null;draw(context)});const form=host.querySelector('#hold-form');if(!form)return;form.addEventListener('submit',async event=>{event.preventDefault();setBusy(form,true);const fd=new FormData(form),start=new Date(fd.get('starts_at')),end=new Date(fd.get('ends_at'));if(end<=start){notify('The end time must be after the start time.');setBusy(form,false);return}const values={contact_name:fd.get('contact_name').trim(),venue:fd.get('venue').trim()||null,starts_at:start.toISOString(),ends_at:end.toISOString(),expires_at:fd.get('expires_at')?new Date(fd.get('expires_at')).toISOString():null,status:fd.get('status'),operational_notes:fd.get('operational_notes').trim()||null};try{const saved=await saveRow(client,'date_holds',values,form.dataset.id||null);selected=saved.id;notify('Date hold saved.');await draw(context)}catch(error){notify(error.message);setBusy(form,false)}});form.querySelector('[data-delete]')?.addEventListener('click',async()=>{if(!confirm('Delete this date hold permanently?'))return;try{await deleteRow(client,'date_holds',form.dataset.id);selected=null;notify('Date hold deleted.');await draw(context)}catch(error){notify(error.message)}})}
export async function mountHolds(context){selected=null;await draw(context)}
