/* PEAK_FINANCE — full school finance: inflow/outflow, expenses, surplus, assets (head + bursar only) */
window.PEAK_FINANCE = (function () {
  const { useState, useEffect } = React;
  const T = window.V4.T;
  const WK = 'https://nextos-sentinel.nextafricaai.workers.dev';
  function tenant() { const p = (window.PEAK_ROLE && window.PEAK_ROLE.getProfile && window.PEAK_ROLE.getProfile()); return (p && p.tenantId) || 'peak-primary'; }
  function me() { const p = (window.PEAK_ROLE && window.PEAK_ROLE.getProfile && window.PEAK_ROLE.getProfile()); return (p && (p.fullName || p.email)) || ''; }
  const fmt = n => 'UGX ' + (Number(n) || 0).toLocaleString();
  const EXP_CATS = ['salaries', 'allowances', 'food', 'maintenance', 'utilities', 'supplies', 'transport', 'events', 'other'];
  const INC_CATS = ['donation', 'grant', 'events', 'other'];
  const ASSET_CATS = ['building', 'vehicle', 'equipment', 'furniture', 'land', 'it', 'other'];
  const CAT_LABEL = { salaries: 'Salaries & wages', allowances: 'Allowances', food: 'Food & meals', maintenance: 'Maintenance & repairs', utilities: 'Utilities (water/power)', supplies: 'Supplies & materials', transport: 'Transport & fuel', events: 'Events facilitation', donation: 'Donation', grant: 'Grant', other: 'Other' };
  // The unavoidable running costs every school carries. They sit in the budget waiting for the head/bursar to fund them.
  const ESSENTIALS = [
    { key: 'food', label: 'Food & meals' }, { key: 'water', label: 'Water' }, { key: 'utilities', label: 'Electricity / power' },
    { key: 'internet', label: 'Internet / WiFi' }, { key: 'security', label: 'Security' }, { key: 'cleaning', label: 'Cleaning & sanitation' },
    { key: 'supplies', label: 'Stationery & supplies' }, { key: 'transport', label: 'Transport & fuel' }, { key: 'maintenance', label: 'Maintenance & repairs' },
  ];

  function _vchNo() { const y = new Date().getFullYear(); return 'PV-' + y + '-' + String(Date.now()).slice(-6); }
  function payReceiptPdf(rec) {
    try {
      const ctor = (window.jspdf && window.jspdf.jsPDF) || window.jsPDF; if (!ctor) return false;
      const doc = new ctor({ unit: 'pt', format: 'a4' }); const W = doc.internal.pageSize.getWidth();
      const brand = (window.__BRAND_NAME) || 'School';
      doc.setFillColor(10, 16, 41); doc.rect(0, 0, W, 74, 'F');
      doc.setTextColor(255, 255, 255); doc.setFontSize(17); doc.setFont(undefined, 'bold'); doc.text(brand, 40, 40);
      doc.setFontSize(10); doc.setFont(undefined, 'normal'); doc.text(rec.kindLabel || 'Payment Receipt', 40, 58);
      doc.setTextColor(25, 25, 25); let y = 118;
      const row = (k, v) => { doc.setFont(undefined, 'bold'); doc.setFontSize(10.5); doc.text(k, 40, y); doc.setFont(undefined, 'normal'); doc.text(String(v == null || v === '' ? '—' : v), 210, y); y += 26; };
      row('Receipt No', rec.receiptNo);
      row('Date', rec.date);
      row('Paid to', rec.payee);
      row('Purpose', rec.purpose);
      row('Method', rec.method);
      row('Amount', 'UGX ' + Number(rec.amount || 0).toLocaleString());
      y += 8; doc.setDrawColor(220, 220, 220); doc.line(40, y, W - 40, y); y += 28;
      doc.setFontSize(9); doc.setTextColor(120, 120, 120);
      doc.text('Issued by ' + (rec.issuedBy || '') + (rec.payType === 'longterm' ? '  (long-term — see bank statement)' : '') + '  ·  Generated by NEXT OS', 40, y);
      doc.save((rec.receiptNo || 'receipt') + '.pdf');
      return true;
    } catch (e) { return false; }
  }

  function FModal({ title, onClose, children }) {
    return (
      <div onClick={onClose} style={{ position: 'fixed', inset: 0, zIndex: 800, background: 'rgba(5,8,22,0.7)', backdropFilter: 'blur(6px)', display: 'grid', placeItems: 'center', padding: 20 }}>
        <div onClick={e => e.stopPropagation()} style={{ background: T.surface, border: '1px solid ' + T.borderStr, borderRadius: 16, width: '100%', maxWidth: 460, maxHeight: '92vh', overflow: 'auto' }}>
          <div style={{ padding: '18px 22px', borderBottom: '1px solid ' + T.border, fontSize: 15, fontWeight: 700, color: T.ink }}>{title}</div>
          {children}
        </div>
      </div>
    );
  }
  function SupportAdder({ onAdd, T, card }) {
    const [n, setN] = useState(''); const [r, setR] = useState(''); const [m, setM] = useState('');
    const inp = { background: T.bg, border: '1px solid ' + T.border, borderRadius: 8, padding: '8px 10px', fontSize: 12.5, color: T.ink, outline: 'none' };
    return (
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
        <input value={n} onChange={e => setN(e.target.value)} placeholder="Name" style={{ ...inp, flex: '1 1 150px' }} />
        <input value={r} onChange={e => setR(e.target.value)} placeholder="Role (e.g. Cook)" style={{ ...inp, flex: '1 1 130px' }} />
        <input value={m} onChange={e => setM(e.target.value)} placeholder="Monthly UGX" style={{ ...inp, width: 120 }} />
        <button onClick={() => { onAdd(n, r, m); setN(''); setR(''); setM(''); }} style={{ background: T.green || '#00c389', color: '#062b18', border: 'none', borderRadius: 8, padding: '8px 16px', fontSize: 12.5, fontWeight: 700, cursor: 'pointer' }}>+ Add</button>
      </div>
    );
  }

  function NiaExpenseGuard({ ctx, onCancel, onConfirm }) {
    const [purpose, setPurpose] = useState('');
    const inp = { background: T.bg, border: '1px solid ' + T.border, borderRadius: 8, padding: '10px 12px', fontSize: 13.5, color: T.ink, fontFamily: T.font, outline: 'none', width: '100%' };
    const tone = ctx.level === 'bankrupt' ? '#ff5a72' : ctx.level === 'deficit' ? (T.warn || '#e8a23a') : (T.gold || '#d8a200');
    const canGo = !ctx.needPurpose || purpose.trim().length > 1;
    const Row = (l, v, c) => (<div style={{ display: 'flex', justifyContent: 'space-between', padding: '7px 0', borderBottom: '1px solid ' + T.border }}><span style={{ fontSize: 12.5, color: T.ink3 }}>{l}</span><span style={{ fontSize: 13, fontWeight: 700, color: c || T.ink, fontVariantNumeric: 'tabular-nums' }}>{v}</span></div>);
    return (
      <FModal title="Nia — let me flag this first" onClose={onCancel}>
        <div style={{ padding: '18px 22px' }}>
          <div style={{ display: 'flex', gap: 11, marginBottom: 14, alignItems: 'flex-start' }}>
            <span style={{ width: 30, height: 30, borderRadius: 8, background: tone, color: '#1a0a0e', display: 'grid', placeItems: 'center', fontFamily: T.mono, fontSize: 11, fontWeight: 800, flexShrink: 0 }}>AI</span>
            <div style={{ fontSize: 13.5, lineHeight: 1.6, color: T.ink }}>{ctx.message}</div>
          </div>
          <div style={{ background: T.bg, border: '1px solid ' + T.border, borderRadius: 10, padding: '4px 14px', marginBottom: 14 }}>
            {Row('Money in this term', fmt(ctx.totalIn), T.green || '#00c389')}
            {Row('This expense', '− ' + fmt(ctx.amt), tone)}
            {Row('Balance after', fmt(ctx.newNet), ctx.newNet < 0 ? '#ff5a72' : T.ink)}
          </div>
          {ctx.needPurpose && (
            <div style={{ marginBottom: 14 }}>
              <div style={{ fontSize: 12.5, color: T.ink2, marginBottom: 6 }}>This is going under <b>“Other”</b>. What exactly is the {fmt(ctx.amt)} for — and which event or activity does it belong to?</div>
              <input autoFocus value={purpose} onChange={e => setPurpose(e.target.value)} placeholder="e.g. Sports Gala transport & meals" style={inp} />
            </div>
          )}
          <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
            <button onClick={onCancel} style={{ background: 'transparent', border: '1px solid ' + T.border, color: T.ink2, borderRadius: 9, padding: '10px 18px', fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>Cancel</button>
            <button disabled={!canGo} onClick={() => onConfirm(purpose.trim())} style={{ background: canGo ? tone : T.border, color: canGo ? '#1a0a0e' : T.ink3, border: 'none', borderRadius: 9, padding: '10px 18px', fontSize: 13, fontWeight: 700, cursor: canGo ? 'pointer' : 'default' }}>{ctx.level === 'bankrupt' ? 'Record anyway' : 'Yes, record it'}</button>
          </div>
        </div>
      </FModal>
    );
  }

  function Finance() {
    const [txns, setTxns] = useState([]);
    const [assets, setAssets] = useState([]);
    const [tab, setTab] = useState('flow');
    const [form, setForm] = useState(null); // {kind} or {asset:true}
    const [busy, setBusy] = useState(false);
    const [teachers, setTeachers] = useState([]);
    const [vouchers, setVouchers] = useState([]);
    const [budget, setBudget] = useState(null);
    const [budgetId, setBudgetId] = useState(null);
    const [budgetBusy, setBudgetBusy] = useState(false);
    const [del, setDel] = useState(null);
    const [staffPay, setStaffPay] = useState({ map: {}, recs: [] });
    const reload = () => {
      fetch(WK + '/finance?tenant=' + encodeURIComponent(tenant())).then(r => r.json()).then(d => { if (d && d.transactions) setTxns(d.transactions); }).catch(() => {});
      fetch(WK + '/assets?tenant=' + encodeURIComponent(tenant())).then(r => r.json()).then(d => { if (d && d.assets) setAssets(d.assets); }).catch(() => {});
      fetch(WK + '/os-data?kind=pay_voucher&tenant=' + encodeURIComponent(tenant())).then(r => r.json()).then(d => { setVouchers(((d && d.records) || []).map(x => Object.assign({ _id: x.id }, x.payload)).sort((a, b) => String(b.date || '').localeCompare(String(a.date || '')))); }).catch(() => {});
      fetch(WK + '/os-data?kind=staff_pay&tenant=' + encodeURIComponent(tenant())).then(r => r.json()).then(d => { const recs = ((d && d.records) || []).map(x => Object.assign({ _id: x.id }, x.payload)); const map = {}; recs.forEach(r => { if (r.key) map[r.key] = r; }); setStaffPay({ map: map, recs: recs }); }).catch(() => {});
      fetch(WK + '/os-data?kind=budget_plan&tenant=' + encodeURIComponent(tenant())).then(r => r.json()).then(d => { const rec = ((d && d.records) || [])[0]; if (rec) { setBudgetId(rec.id); setBudget((rec.payload && rec.payload.lines) || {}); } else setBudget({}); }).catch(() => {});
    };
    useEffect(reload, []);
    useEffect(() => { fetch(WK + '/teachers?tenant=' + encodeURIComponent(tenant())).then(r => r.ok ? r.json() : null).then(d => { if (d && Array.isArray(d.teachers)) setTeachers(d.teachers.filter(x => x.full_name || x.email)); }).catch(() => {}); }, []);

    const feesCollected = (window.PEAK && window.PEAK.kpis && window.PEAK.kpis.feesCollectedTerm) || 0;
    const otherIncome = txns.filter(t => t.kind === 'income').reduce((a, t) => a + Number(t.amount || 0), 0);
    const totalIn = feesCollected + otherIncome;
    const recordedOut = txns.filter(t => t.kind === 'expense').reduce((a, t) => a + Number(t.amount || 0), 0);
    // Operating spend = recorded expenses that are NOT salary/allowance (meals, maintenance, utilities, supplies, transport, events, other).
    const operatingOut = txns.filter(t => t.kind === 'expense' && t.category !== 'salaries' && t.category !== 'allowances').reduce((a, t) => a + Number(t.amount || 0), 0);
    const assetsValue = assets.reduce((a, x) => a + Number(x.value || 0), 0);
    const byCat = {}; txns.filter(t => t.kind === 'expense').forEach(t => { byCat[t.category || 'other'] = (byCat[t.category || 'other'] || 0) + Number(t.amount || 0); });
    const catRows = Object.keys(byCat).map(k => ({ k, v: byCat[k] })).sort((a, b) => b.v - a.v);
    const maxCat = Math.max(1, ...catRows.map(c => c.v));

    const card = { background: T.surface, border: '1px solid ' + T.border, borderRadius: 12, padding: 18 };
    const btn = (p) => ({ border: p ? 'none' : '1px solid ' + T.borderStr, background: p ? T.red : 'transparent', color: p ? '#fff' : T.ink2, padding: '8px 14px', borderRadius: 9, fontSize: 12.5, fontWeight: 600, cursor: 'pointer' });
    const inp = { background: T.bg, border: '1px solid ' + T.border, borderRadius: 8, padding: '9px 11px', fontSize: 13, color: T.ink, fontFamily: T.font, outline: 'none', width: '100%' };

    const advise = (f, amt) => {
      const newNet = net - amt;
      const pct = totalIn > 0 ? Math.round(amt / totalIn * 100) : 999;
      const needPurpose = (f.category === 'other') && !(f.description || '').trim();
      let level = null, message = '';
      if (amt > totalIn || newNet <= -Math.max(totalIn * 0.5, 1)) { level = 'bankrupt'; message = 'This is more than the school can afford right now. Total money in this term is ' + fmt(totalIn) + ', so a ' + fmt(amt) + ' expense pulls your balance to ' + fmt(newNet) + '. That risks not covering salaries and daily operations — it could put the school in the red. Please double-check this is correct.'; }
      else if (newNet < 0) { level = 'deficit'; message = 'Careful — this tips the school into a deficit. You have ' + fmt(net) + ' available, and this ' + fmt(amt) + ' expense leaves ' + fmt(newNet) + '. Where will the shortfall be covered from?'; }
      else if (pct >= 30) { level = 'large'; message = 'That is a large expense — ' + fmt(amt) + ' is about ' + pct + '% of everything collected so far. You would still have ' + fmt(newNet) + ' left, but it is worth a second look.'; }
      if (!level && !needPurpose) return null;
      if (!message) message = 'Quick check before I record this so the books stay clear.';
      return { f, amt, totalIn, net, newNet, level, message, needPurpose };
    };
    const saveTxn = (f) => {
      if (f.kind === 'expense') {
        const amt0 = Number(String(f.amount).replace(/[^0-9]/g, ''));
        if (amt0) {
          const adv = advise(f, amt0);
          if (adv) {
            window.peakModal && window.peakModal.open(React.createElement(NiaExpenseGuard, {
              ctx: adv,
              onCancel: () => window.peakModal && window.peakModal.close(),
              onConfirm: (purpose) => {
                window.peakModal && window.peakModal.close();
                const f2 = purpose ? Object.assign({}, f, { description: ((f.description || '') + (f.description ? ' · ' : '') + purpose), category: f.category }) : f;
                try { if (window.NIA_FEED && (adv.level === 'bankrupt' || adv.level === 'deficit')) window.NIA_FEED.post({ key: 'bigexp-' + Date.now(), level: 'alert', icon: '\uD83D\uDCB8', title: 'Big expense recorded', body: 'You approved a ' + fmt(amt0) + ' expense I flagged \u2014 balance is now ' + fmt(adv.newNet) + '. I\'ll keep watch on the budget.', cta: { label: 'Open Finance', route: 'finance' } }); } catch (e) {}
                commitTxn(f2);
              }
            }));
            return;
          }
        }
      }
      commitTxn(f);
    };
    const commitTxn = (f) => {
      const amt = Number(String(f.amount).replace(/[^0-9]/g, '')); if (!amt) { window.peakToast && window.peakToast('Enter an amount', 'info'); return; }
      if (f.id) {
        setBusy(true);
        fetch(WK + '/finance/update', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tenant_id: tenant(), id: f.id, txn: { kind: f.kind, category: f.category, description: (f.description || ''), amount: amt, method: f.method, occurred_at: f.date } }) })
          .then(r => r.json()).then(res => { setBusy(false); setForm(null); reload(); if (res && res.error) window.peakToast && window.peakToast('Could not update', 'info', res.error); else window.peakToast && window.peakToast('Transaction updated', 'success', fmt(amt)); }).catch(() => setBusy(false));
        return;
      }
      const isExpense = f.kind === 'expense';
      const payee = (f.payeeName || '').trim();
      if (isExpense && f.category === 'salaries' && !payee) { window.peakToast && window.peakToast('Choose who is being paid', 'info'); return; }
      const payType = f.payType || 'instant';
      const desc = (f.description || '') + (payee ? ((f.description ? ' · ' : '') + 'Paid to ' + payee) : '');
      setBusy(true);
      fetch(WK + '/finance/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tenant_id: tenant(), txn: { kind: f.kind, category: f.category, description: desc, amount: amt, method: f.method, occurred_at: f.date, created_by: me() } }) })
        .then(r => r.json()).then(res => {
          if (res.error) { setBusy(false); window.peakToast && window.peakToast('Could not save', 'info', res.error); return; }
          if (!isExpense) { setBusy(false); setForm(null); reload(); window.peakToast && window.peakToast('Income recorded', 'success', fmt(amt) + ' · ' + (CAT_LABEL[f.category] || f.category)); return; }
          // Expense → create a stored voucher (receipt for instant, statement entry for long-term)
          const receiptNo = _vchNo();
          const voucher = { receiptNo: receiptNo, payee: payee || (CAT_LABEL[f.category] || f.category), payeeEmail: (f.payeeEmail || '').toLowerCase(), category: f.category, purpose: f.description || (CAT_LABEL[f.category] || f.category), amount: amt, method: f.method || 'cash', date: f.date, payType: payType, status: payType === 'instant' ? 'paid' : 'pending', issuedBy: me(), kindLabel: f.category === 'salaries' ? 'Salary Payment Receipt' : 'Payment Receipt', createdAt: new Date().toISOString() };
          fetch(WK + '/os-data/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'pay_voucher', tenant: tenant(), record: voucher }) })
            .then(r => r.json()).then(() => {
              setBusy(false); setForm(null); reload();
              if (payType === 'instant') { payReceiptPdf(voucher); window.peakToast && window.peakToast('Paid · receipt generated', 'success', payee + ' · ' + fmt(amt)); }
              else { window.peakToast && window.peakToast('Recorded to bank statement', 'success', payee + ' · ' + fmt(amt) + ' · pending'); }
            }).catch(() => { setBusy(false); setForm(null); reload(); });
        }).catch(() => setBusy(false));
    };
    const doDeleteTxn = (t) => {
      fetch(WK + '/finance/delete', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tenant_id: tenant(), id: t.id }) })
        .then(r => r.json()).then(res => { setDel(null); reload(); if (res && res.error) window.peakToast && window.peakToast('Could not delete', 'info', res.error); else window.peakToast && window.peakToast('Transaction deleted', 'success', (CAT_LABEL[t.category] || t.category)); }).catch(() => setDel(null));
    };
    const setBudgetLine = (key, val) => { const v = Number(String(val).replace(/[^0-9]/g, '')) || 0; setBudget(Object.assign({}, budget || {}, { [key]: v })); };
    const saveBudget = () => {
      setBudgetBusy(true);
      const payload = { lines: budget || {}, period: 'term', updatedAt: new Date().toISOString(), by: me() };
      const body = budgetId ? { kind: 'budget_plan', tenant: tenant(), record: payload, id: budgetId } : { kind: 'budget_plan', tenant: tenant(), record: payload };
      fetch(WK + '/os-data/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
        .then(r => r.json()).then(res => { setBudgetBusy(false); if (res && res.record && res.record.id) setBudgetId(res.record.id); try { window.__BUDGET_PLAN = payload; } catch (e) {} window.peakToast && window.peakToast('Budget saved', 'success', 'Nia will hold spending against it.'); }).catch(() => setBudgetBusy(false));
    };
    const budgetReview = () => {
      const plan = budget || {};
      const essentialsBudget = ESSENTIALS.reduce((a, e) => a + (Number(plan[e.key]) || 0), 0);
      const planned = essentialsBudget + wageBill;
      const remaining = totalIn - planned;
      const unfunded = ESSENTIALS.filter(e => !(Number(plan[e.key]) > 0));
      const insights = [];
      if (unfunded.length) insights.push({ tone: 'warn', text: 'These running costs have no budget yet: ' + unfunded.map(e => e.label).join(', ') + '.', sug: 'They are unavoidable — fund them before any one-off spending.' });
      if (totalIn > 0 && planned > totalIn) insights.push({ tone: 'bad', text: 'Your plan spends ' + fmt(planned) + ' but only ' + fmt(totalIn) + ' has come in — ' + fmt(planned - totalIn) + ' short.', sug: 'On a fixed income that is a deficit. Trim the biggest controllable lines, or collect outstanding fees before you commit.' });
      const funded = ESSENTIALS.map(e => ({ label: e.label, v: Number(plan[e.key]) || 0 })).filter(x => x.v > 0).sort((a, b) => b.v - a.v);
      if (funded[0] && essentialsBudget > 0) { const top = funded[0]; const pc = Math.round(top.v / essentialsBudget * 100); insights.push({ tone: 'tip', text: top.label + ' is ' + pc + '% of your running costs (' + fmt(top.v) + ').', sug: 'Your biggest lever — a 10% supplier deal saves about ' + fmt(Math.round(top.v * 0.1)) + ' a term.' }); }
      const discCats = Object.keys(byCat).filter(k => k !== 'salaries' && k !== 'allowances' && !ESSENTIALS.some(e => e.key === k));
      const disc = discCats.reduce((a, k) => a + byCat[k], 0);
      if (disc > 0) insights.push({ tone: 'warn', text: 'You have already spent ' + fmt(disc) + ' on one-off / discretionary items this term.', sug: 'On a fixed income every extra cost competes with salaries and meals — question each one.' });
      const studs = (window.PEAK && window.PEAK.students) || [];
      const outstanding = studs.reduce((a, x) => a + Math.max(0, Number(x.balance) || 0), 0);
      if (outstanding > 0) insights.push({ tone: 'tip', text: fmt(outstanding) + ' in fees is still uncollected.', sug: 'Collecting it funds this whole budget without cutting a thing — start with the biggest balances.' });
      if (remaining > 0 && planned > 0) insights.push({ tone: 'good', text: 'You have ' + fmt(remaining) + ' unallocated after essentials and salaries.', sug: 'Keep 5–10% as a buffer — a fixed income has no safety net.' });
      // proactively nudge once a day when the plan is over income
      try { if (window.NIA_FEED && totalIn > 0 && planned > totalIn) window.NIA_FEED.post({ key: 'budget-deficit-' + new Date().toISOString().slice(0,10), level: 'alert', icon: '\uD83D\uDCCA', title: 'Budget runs over income', body: 'Your planned spend is ' + fmt(planned - totalIn) + ' more than your income. On a fixed income that bites — want to review where to trim?', cta: { label: 'Open budget', route: 'finance' }, toast: false }); } catch (e) {}
      return { essentialsBudget, planned, remaining, unfunded, insights };
    };
    const markVoucherPaid = (v) => {
      const rec = Object.assign({}, v, { status: 'paid', paidAt: new Date().toISOString(), payType: 'instant' }); delete rec._id;
      fetch(WK + '/os-data/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'pay_voucher', tenant: tenant(), record: rec, id: v._id }) })
        .then(r => r.json()).then(() => { payReceiptPdf(rec); reload(); window.peakToast && window.peakToast('Marked paid · receipt generated', 'success', v.payee); }).catch(() => {});
    };
    const ym = new Date().toISOString().slice(0, 7);
    const monthLabel = new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });
    const savePay = (rec, id) => fetch(WK + '/os-data/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(id ? { kind: 'staff_pay', tenant: tenant(), record: rec, id: id } : { kind: 'staff_pay', tenant: tenant(), record: rec }) }).then(r => r.json());
    const setMonthly = (st, amount) => {
      const amt = Number(String(amount).replace(/[^0-9]/g, '')) || 0;
      const existing = staffPay.map[st.key];
      const rec = { key: st.key, name: st.name, role: st.role, type: st.type, email: st.email || '', monthly: amt, allowance: (existing && existing.allowance) || st.allowance || 0 };
      savePay(rec, existing && existing._id).then(() => reload());
    };
    const setAllowance = (st, amount) => {
      const amt = Number(String(amount).replace(/[^0-9]/g, '')) || 0;
      const existing = staffPay.map[st.key];
      const rec = { key: st.key, name: st.name, role: st.role, type: st.type, email: st.email || '', monthly: (existing && existing.monthly) || st.monthly || 0, allowance: amt };
      savePay(rec, existing && existing._id).then(() => reload());
    };
    const addSupport = (name, role, monthly) => {
      if (!name.trim()) { window.peakToast && window.peakToast('Enter a name', 'info'); return; }
      const rec = { key: 'sup-' + Date.now(), name: name.trim(), role: role.trim() || 'Support staff', type: 'support', email: '', monthly: Number(String(monthly).replace(/[^0-9]/g, '')) || 0 };
      savePay(rec).then(() => reload());
    };
    const payStaff = (st) => {
      const due = (st.monthly || 0) + (st.allowance || 0);
      setForm({ kind: 'expense', category: 'salaries', payeeName: st.name, payeeEmail: st.email || '', amount: String(due), date: new Date().toISOString().slice(0, 10), payType: 'instant', description: monthLabel + ' pay' + (st.allowance ? ' (salary ' + fmt(st.monthly || 0) + ' + allowance ' + fmt(st.allowance) + ')' : '') });
    };
    const paidThisMonth = (name) => vouchers.some(v => (v.payee || '').toLowerCase() === (name || '').toLowerCase() && String(v.date || '').slice(0, 7) === ym);
    const payrollList = (function () {
      const teaching = (teachers || []).map(t => ({ key: (t.email || t.full_name), name: t.full_name || t.email, email: t.email || '', role: ((t.subjects && t.subjects.length) ? ('Teacher · ' + t.subjects.join('/')) : 'Teacher'), type: 'teaching' }));
      const support = (staffPay.recs || []).filter(r => r.type === 'support').map(r => ({ key: r.key, name: r.name, email: '', role: r.role || 'Support staff', type: 'support' }));
      return teaching.concat(support).map(st => { const p = staffPay.map[st.key]; return Object.assign({}, st, { monthly: (p && p.monthly) || 0, allowance: (p && p.allowance) || 0, paid: paidThisMonth(st.name) }); });
    })();
    const payrollTotal = payrollList.reduce((a, s) => a + (s.monthly || 0), 0);
    const allowanceTotal = payrollList.reduce((a, s) => a + (s.allowance || 0), 0);
    const wageBill = payrollTotal + allowanceTotal;
    const paidTotal = payrollList.filter(s => s.paid).reduce((a, s) => a + (s.monthly || 0) + (s.allowance || 0), 0);
    const needSalary = payrollList.filter(s => !s.monthly).length;
    const unpaidCount = payrollList.filter(s => s.monthly > 0 && !s.paid).length;
    // ── Total outflow = full monthly wage bill (all salaries + allowances, teaching + non-teaching) + operating spend (meals & other operations). ──
    const totalOut = wageBill + operatingOut;
    const net = totalIn - totalOut;
    const saveAsset = (f) => {
      if (!f.name) { window.peakToast && window.peakToast('Enter a name', 'info'); return; } setBusy(true);
      fetch(WK + '/assets/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tenant_id: tenant(), asset: { name: f.name, category: f.category, value: Number(String(f.value).replace(/[^0-9]/g, '')) || 0, condition: f.condition, acquired: f.acquired, notes: f.notes } }) })
        .then(r => r.json()).then(res => { setBusy(false); if (res.error) { window.peakToast && window.peakToast('Could not save', 'info', res.error); return; } setForm(null); reload(); window.peakToast && window.peakToast('Asset added', 'success', f.name); }).catch(() => setBusy(false));
    };

    const SummaryCard = (label, val, color) => (
      <div style={{ ...card, padding: 16 }}>
        <div style={{ fontSize: 10.5, color: T.ink3, fontFamily: T.mono, letterSpacing: '0.05em', fontWeight: 600 }}>{label.toUpperCase()}</div>
        <div style={{ fontSize: 21, fontWeight: 700, color: color || T.ink, marginTop: 6, fontVariantNumeric: 'tabular-nums' }}>{fmt(val)}</div>
      </div>
    );

    return (
      <div style={{ height: '100%', overflow: 'auto', background: T.bg, color: T.ink, fontFamily: T.font, fontSize: 13 }}>
        <header style={{ padding: '22px 28px 16px', borderBottom: '1px solid ' + T.border, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
          <div>
            <div style={{ fontSize: 11, color: T.ink3, fontFamily: T.mono, letterSpacing: '0.08em', fontWeight: 600, marginBottom: 8 }}>FINANCE · HEAD TEACHER & BURSAR ONLY</div>
            <div style={{ fontSize: 24, fontWeight: 700, letterSpacing: '-0.02em' }}>Money</div>
            <div style={{ fontSize: 13, color: T.ink3, marginTop: 4 }}>Cash in and out, expenses, surplus and assets — the full financial picture.</div>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button style={btn(false)} onClick={() => setForm({ kind: 'income', category: 'donation', date: new Date().toISOString().slice(0, 10) })}>+ Income</button>
            <button style={btn(true)} onClick={() => setForm({ kind: 'expense', category: 'maintenance', date: new Date().toISOString().slice(0, 10) })}>+ Expense</button>
          </div>
        </header>

        <div style={{ padding: 24 }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 12, marginBottom: 18 }}>
            {SummaryCard('Total inflow', totalIn, T.good)}
            <div style={{ ...card, padding: 16 }} title="Salaries + allowances for all staff, plus meals and other operating spend">
              <div style={{ fontSize: 10.5, color: T.ink3, fontFamily: T.mono, letterSpacing: '0.05em', fontWeight: 600 }}>TOTAL OUTFLOW</div>
              <div style={{ fontSize: 21, fontWeight: 700, color: T.redInk, marginTop: 6, fontVariantNumeric: 'tabular-nums' }}>{fmt(totalOut)}</div>
              <div style={{ fontSize: 10, color: T.ink4, fontFamily: T.mono, marginTop: 6, lineHeight: 1.5 }}>Salaries {fmt(payrollTotal)} · Allowances {fmt(allowanceTotal)}<br/>Operations {fmt(operatingOut)}</div>
            </div>
            {SummaryCard('Net surplus', net, net >= 0 ? T.good : T.redInk)}
            {SummaryCard('Assets value', assetsValue, T.ink)}
          </div>

          <div style={{ display: 'flex', gap: 6, marginBottom: 16 }}>
            {[['flow', 'Cash flow'], ['budget', 'Budget'], ['expenses', 'Expenses'], ['payroll', 'Payroll'], ['vouchers', 'Receipts & statement'], ['assets', 'Assets']].map(o => (
              <button key={o[0]} onClick={() => setTab(o[0])} style={{ border: 'none', background: tab === o[0] ? T.surface2 : 'transparent', color: tab === o[0] ? T.ink : T.ink3, padding: '8px 16px', borderRadius: 8, fontSize: 12.5, fontWeight: 600, cursor: 'pointer' }}>{o[1]}</button>
            ))}
          </div>

          {tab === 'flow' && (
            <div style={card}>
              <div style={{ fontSize: 11, color: T.ink3, fontFamily: T.mono, marginBottom: 10 }}>FEES COLLECTED (from fee system): <span style={{ color: T.good }}>{fmt(feesCollected)}</span> · then your manual entries below</div>
              {txns.length === 0 ? <div style={{ color: T.ink4, fontSize: 13, padding: '8px 0' }}>No transactions yet. Add income or an expense above.</div> : (
                <div style={{ border: '1px solid ' + T.border, borderRadius: 10, overflow: 'hidden' }}>
                  {txns.slice(0, 40).map((t, i) => (
                    <div key={t.id || i} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '11px 14px', borderBottom: i < Math.min(txns.length, 40) - 1 ? '1px solid ' + T.border : 'none' }}>
                      <span style={{ width: 8, height: 8, borderRadius: '50%', background: t.kind === 'income' ? T.good : T.redInk, flexShrink: 0 }} />
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ fontSize: 13, color: T.ink }}>{CAT_LABEL[t.category] || t.category}{t.description ? <span style={{ color: T.ink3 }}> · {t.description}</span> : null}</div>
                        <div style={{ fontSize: 11, color: T.ink4, fontFamily: T.mono }}>{t.occurred_at}{t.method ? (' · ' + t.method) : ''}{t.created_by ? (' · ' + t.created_by) : ''}</div>
                      </div>
                      <div style={{ fontSize: 14, fontWeight: 700, color: t.kind === 'income' ? T.good : T.redInk, fontVariantNumeric: 'tabular-nums' }}>{t.kind === 'income' ? '+' : '−'}{fmt(t.amount)}</div>
                      {t.id ? <button title="Edit" onClick={() => setForm({ id: t.id, kind: t.kind, category: t.category, amount: String(t.amount), date: t.occurred_at, method: t.method || 'cash', description: t.description || '', payType: 'instant' })} style={{ background: 'transparent', border: '1px solid ' + T.border, color: T.ink3, borderRadius: 7, padding: '5px 9px', fontSize: 11, cursor: 'pointer' }}>Edit</button> : null}
                      {t.id ? <button title="Delete" onClick={() => setDel(t)} style={{ background: 'transparent', border: '1px solid ' + T.border, color: T.ink3, borderRadius: 7, padding: '5px 8px', fontSize: 12, cursor: 'pointer' }}>✕</button> : null}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {tab === 'budget' && (() => {
            const rv = budgetReview();
            const toneC = (t) => t === 'bad' ? '#ff5a72' : t === 'warn' ? (T.warn || '#e8a23a') : t === 'good' ? (T.green || '#00c389') : (T.gold || '#d8a200');
            return (
              <div style={{ display: 'grid', gap: 16 }}>
                <div style={{ ...card, border: '1px solid ' + (rv.planned > totalIn && totalIn > 0 ? '#7a2230' : T.border) }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                    <span style={{ width: 28, height: 28, borderRadius: 8, background: T.red, color: '#fff', display: 'grid', placeItems: 'center', fontFamily: T.mono, fontSize: 10.5, fontWeight: 800 }}>AI</span>
                    <div style={{ fontSize: 14, fontWeight: 700 }}>Nia’s budget review</div>
                  </div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 10, marginBottom: 14 }}>
                    {[['Income (this term)', totalIn, T.green || '#00c389'], ['Planned (essentials + salaries)', rv.planned, T.ink], ['Left after plan', rv.remaining, rv.remaining < 0 ? '#ff5a72' : T.ink]].map((x, i) => (
                      <div key={i} style={{ background: T.bg, border: '1px solid ' + T.border, borderRadius: 10, padding: '10px 12px' }}>
                        <div style={{ fontSize: 10, color: T.ink3, fontFamily: T.mono, letterSpacing: '0.04em' }}>{String(x[0]).toUpperCase()}</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: x[2], marginTop: 4, fontVariantNumeric: 'tabular-nums' }}>{fmt(x[1])}</div>
                      </div>
                    ))}
                  </div>
                  {rv.insights.length === 0 ? <div style={{ fontSize: 13, color: T.ink3 }}>Looking healthy — fund the essentials below and I’ll keep watch.</div> : rv.insights.map((ins, i) => (
                    <div key={i} style={{ display: 'flex', gap: 10, padding: '10px 0', borderTop: i ? '1px solid ' + T.border : 'none' }}>
                      <span style={{ width: 6, height: 6, borderRadius: 3, background: toneC(ins.tone), marginTop: 6, flexShrink: 0 }} />
                      <div><div style={{ fontSize: 13, color: T.ink, lineHeight: 1.5 }}>{ins.text}</div><div style={{ fontSize: 12, color: T.ink3, marginTop: 2 }}>→ {ins.sug}</div></div>
                    </div>
                  ))}
                </div>
                <div style={card}>
                  <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4 }}>The must-pay list — assign a budget</div>
                  <div style={{ fontSize: 12, color: T.ink3, marginBottom: 14 }}>These costs are unavoidable. Set what each gets this term; Nia holds your spending against it.</div>
                  {ESSENTIALS.map(e => { const spent = byCat[e.key] || 0; const b = Number((budget || {})[e.key]) || 0; const over = spent > b && b > 0; return (
                    <div key={e.key} style={{ display: 'grid', gridTemplateColumns: '1fr 130px 120px', gap: 10, alignItems: 'center', padding: '8px 0', borderBottom: '1px solid ' + T.border }}>
                      <div><div style={{ fontSize: 13, color: T.ink }}>{e.label}</div><div style={{ fontSize: 11, color: over ? '#ff5a72' : T.ink4, fontFamily: T.mono }}>{b > 0 ? ('spent ' + fmt(spent) + ' of ' + fmt(b) + (over ? ' · OVER' : '')) : 'not funded yet'}</div></div>
                      <input value={b ? String(b) : ''} onChange={ev => setBudgetLine(e.key, ev.target.value)} placeholder="0" style={{ ...inp, fontFamily: T.mono }} />
                      <div style={{ height: 7, background: T.surface2, borderRadius: 4, overflow: 'hidden' }}><div style={{ height: '100%', width: Math.min(100, b > 0 ? Math.round(spent / b * 100) : 0) + '%', background: over ? '#ff5a72' : (T.green || '#00c389') }} /></div>
                    </div>
                  ); })}
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 14 }}>
                    <div style={{ fontSize: 12.5, color: T.ink2 }}>Essentials total: <b style={{ color: T.ink }}>{fmt(rv.essentialsBudget)}</b></div>
                    <button onClick={saveBudget} disabled={budgetBusy} style={btn(true)}>{budgetBusy ? 'Saving…' : 'Save budget'}</button>
                  </div>
                </div>
              </div>
            );
          })()}

          {tab === 'expenses' && (
            <div style={card}>
              <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 14 }}>Expenses by category · {fmt(totalOut)} total</div>
              {catRows.length === 0 ? <div style={{ color: T.ink4, fontSize: 13 }}>No expenses recorded yet.</div> : catRows.map(c => (
                <div key={c.k} style={{ marginBottom: 12 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12.5, marginBottom: 5 }}>
                    <span style={{ color: T.ink2 }}>{CAT_LABEL[c.k] || c.k}</span>
                    <span style={{ color: T.ink, fontWeight: 600 }}>{fmt(c.v)}</span>
                  </div>
                  <div style={{ height: 8, background: T.surface2, borderRadius: 4, overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: Math.round(c.v / maxCat * 100) + '%', background: T.redInk, borderRadius: 4 }} />
                  </div>
                </div>
              ))}
            </div>
          )}

          {tab === 'vouchers' && (() => {
            const instant = vouchers.filter(v => v.payType !== 'longterm' && v.status === 'paid');
            const pending = vouchers.filter(v => v.payType === 'longterm' || v.status === 'pending');
            const Row = (v, withAction) => (
              <div key={v._id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '11px 14px', borderBottom: '1px solid ' + T.border }}>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 13, color: T.ink, fontWeight: 600 }}>{v.payee} <span style={{ color: T.ink3, fontWeight: 400 }}>· {CAT_LABEL[v.category] || v.category}</span></div>
                  <div style={{ fontSize: 11, color: T.ink4, fontFamily: T.mono }}>{v.receiptNo} · {v.date}{v.method ? (' · ' + v.method) : ''}{v.purpose ? (' · ' + v.purpose) : ''}</div>
                </div>
                <div style={{ fontSize: 14, fontWeight: 700, color: T.redInk, fontVariantNumeric: 'tabular-nums' }}>{fmt(v.amount)}</div>
                {withAction === 'download' ? <button onClick={() => payReceiptPdf(v)} style={{ ...btn(false), padding: '6px 11px', fontSize: 11.5 }}>Receipt</button> : null}
                {withAction === 'pay' ? <button onClick={() => markVoucherPaid(v)} style={{ ...btn(true), padding: '6px 11px', fontSize: 11.5 }}>Mark paid</button> : null}
              </div>
            );
            return (
              <div style={{ display: 'grid', gap: 16 }}>
                <div style={card}>
                  <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4 }}>Receipts · instant payments</div>
                  <div style={{ fontSize: 11.5, color: T.ink3, marginBottom: 12 }}>Money already paid out. Each has a downloadable receipt.</div>
                  {instant.length === 0 ? <div style={{ color: T.ink4, fontSize: 13 }}>No instant payments yet.</div> : <div style={{ border: '1px solid ' + T.border, borderRadius: 10, overflow: 'hidden' }}>{instant.map(v => Row(v, 'download'))}</div>}
                </div>
                <div style={card}>
                  <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4 }}>Bank statement · long-term & pending</div>
                  <div style={{ fontSize: 11.5, color: T.ink3, marginBottom: 12 }}>Scheduled or deferred payments. Mark paid when the bank clears it — a receipt is generated.</div>
                  {pending.length === 0 ? <div style={{ color: T.ink4, fontSize: 13 }}>Nothing pending.</div> : <div style={{ border: '1px solid ' + T.border, borderRadius: 10, overflow: 'hidden' }}>{pending.map(v => Row(v, 'pay'))}</div>}
                </div>
              </div>
            );
          })()}

          {tab === 'payroll' && (
            <div style={{ display: 'grid', gap: 16 }}>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 12 }}>
                {SummaryCard('Wage bill / month', wageBill, T.ink)}
                {SummaryCard('Paid · ' + monthLabel, paidTotal, T.good)}
                {SummaryCard('Still to pay', wageBill - paidTotal, (wageBill - paidTotal) > 0 ? T.redInk : T.good)}
              </div>

              {(needSalary > 0 || unpaidCount > 0) && (
                <div style={{ ...card, display: 'flex', gap: 12, alignItems: 'flex-start', borderColor: T.warn }}>
                  <span style={{ width: 26, height: 26, borderRadius: 7, background: T.red, color: '#fff', display: 'grid', placeItems: 'center', fontFamily: 'ui-monospace,monospace', fontSize: 11, fontWeight: 700, flexShrink: 0 }}>AI</span>
                  <div style={{ fontSize: 12.5, color: T.ink2, lineHeight: 1.55 }}>
                    {needSalary > 0 ? <div><b style={{ color: T.ink }}>{needSalary} staff have no salary set.</b> Set their monthly pay below so payroll and the budget reflect the real wage bill.</div> : null}
                    {unpaidCount > 0 ? <div style={{ marginTop: needSalary > 0 ? 6 : 0 }}><b style={{ color: T.ink }}>{unpaidCount} staff are unpaid for {monthLabel}.</b> Tap Pay to record it — it deducts from finances and issues a receipt.</div> : null}
                    {(teachers || []).length === 0 ? <div style={{ marginTop: 6 }}>No teachers are in the system yet — import your teaching staff first so they appear on payroll.</div> : null}
                  </div>
                </div>
              )}

              <div style={card}>
                <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4 }}>Staff payments · {monthLabel}</div>
                <div style={{ fontSize: 11.5, color: T.ink3, marginBottom: 12 }}>Teaching and non-teaching staff. Set each monthly pay or allowance; paying records the expense and a receipt.</div>
                {payrollList.length === 0 ? <div style={{ color: T.ink4, fontSize: 13 }}>No staff yet. Import teachers, or add support staff below.</div> : (
                  <div style={{ border: '1px solid ' + T.border, borderRadius: 10, overflow: 'hidden' }}>
                    {payrollList.map((st, i) => (
                      <div key={st.key} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 14px', borderBottom: i < payrollList.length - 1 ? '1px solid ' + T.border : 'none', flexWrap: 'wrap' }}>
                        <div style={{ flex: 1, minWidth: 160 }}>
                          <div style={{ fontSize: 13, color: T.ink, fontWeight: 600 }}>{st.name} {st.type === 'support' ? <span style={{ fontSize: 9.5, color: T.ink3, border: '1px solid ' + T.border, borderRadius: 5, padding: '1px 6px', marginLeft: 6 }}>NON-TEACHING</span> : null}</div>
                          <div style={{ fontSize: 11, color: T.ink3 }}>{st.role}</div>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'flex-end', gap: 10, flexWrap: 'wrap' }}>
                          <label style={{ display: 'block' }}><div style={{ fontSize: 9, color: T.ink4, fontFamily: 'ui-monospace,monospace', marginBottom: 2 }}>SALARY</div>
                            <input defaultValue={st.monthly || ''} placeholder="monthly" onBlur={e => { const v = Number(String(e.target.value).replace(/[^0-9]/g, '')) || 0; if (v !== st.monthly) setMonthly(st, v); }} style={{ width: 100, background: T.bg, border: '1px solid ' + T.border, borderRadius: 8, padding: '7px 9px', fontSize: 12.5, color: T.ink, fontFamily: 'ui-monospace,monospace', outline: 'none' }} /></label>
                          <label style={{ display: 'block' }}><div style={{ fontSize: 9, color: T.ink4, fontFamily: 'ui-monospace,monospace', marginBottom: 2 }}>ALLOWANCE</div>
                            <input defaultValue={st.allowance || ''} placeholder="allowance" onBlur={e => { const v = Number(String(e.target.value).replace(/[^0-9]/g, '')) || 0; if (v !== st.allowance) setAllowance(st, v); }} style={{ width: 100, background: T.bg, border: '1px solid ' + T.border, borderRadius: 8, padding: '7px 9px', fontSize: 12.5, color: T.ink, fontFamily: 'ui-monospace,monospace', outline: 'none' }} /></label>
                        </div>
                        {st.paid
                          ? <span style={{ fontSize: 11.5, color: T.good, fontFamily: 'ui-monospace,monospace', minWidth: 96, textAlign: 'right' }}>✓ Paid {fmt((st.monthly||0)+(st.allowance||0))}</span>
                          : <button onClick={() => payStaff(st)} disabled={!((st.monthly||0)+(st.allowance||0))} style={{ background: ((st.monthly||0)+(st.allowance||0)) ? T.red : 'transparent', color: ((st.monthly||0)+(st.allowance||0)) ? '#fff' : T.ink4, border: ((st.monthly||0)+(st.allowance||0)) ? 'none' : '1px solid ' + T.border, borderRadius: 8, padding: '7px 14px', fontSize: 12, fontWeight: 600, cursor: ((st.monthly||0)+(st.allowance||0)) ? 'pointer' : 'not-allowed', minWidth: 96 }}>Pay {fmt((st.monthly||0)+(st.allowance||0))}</button>}
                      </div>
                    ))}
                  </div>
                )}
                <div style={{ marginTop: 14, paddingTop: 14, borderTop: '1px solid ' + T.border }}>
                  <div style={{ fontSize: 11.5, color: T.ink3, fontFamily: 'ui-monospace,monospace', marginBottom: 8 }}>ADD NON-TEACHING STAFF (cook, guard, driver, cleaner…)</div>
                  {(function () {
                    return <SupportAdder onAdd={addSupport} T={T} card={card} />;
                  })()}
                </div>
              </div>
            </div>
          )}

          {tab === 'assets' && (
            <div style={card}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                <div style={{ fontSize: 13, fontWeight: 700 }}>School assets · {fmt(assetsValue)} total</div>
                <button style={btn(false)} onClick={() => setForm({ asset: true, category: 'equipment', condition: 'good' })}>+ Add asset</button>
              </div>
              {assets.length === 0 ? <div style={{ color: T.ink4, fontSize: 13 }}>No assets registered yet.</div> : (
                <div style={{ border: '1px solid ' + T.border, borderRadius: 10, overflow: 'hidden' }}>
                  {assets.map((a, i) => (
                    <div key={a.id || i} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '11px 14px', borderBottom: i < assets.length - 1 ? '1px solid ' + T.border : 'none' }}>
                      <div style={{ flex: 1 }}><div style={{ fontSize: 13, color: T.ink, fontWeight: 600 }}>{a.name}</div><div style={{ fontSize: 11, color: T.ink4, fontFamily: T.mono }}>{a.category}{a.condition ? (' · ' + a.condition) : ''}</div></div>
                      <div style={{ fontSize: 14, fontWeight: 700, color: T.ink, fontVariantNumeric: 'tabular-nums' }}>{fmt(a.value)}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {del && (
          <FModal title="Delete this transaction?" onClose={() => setDel(null)}>
            <div style={{ padding: 22 }}>
              <div style={{ fontSize: 13.5, color: T.ink2, lineHeight: 1.6, marginBottom: 16 }}>Remove <b>{CAT_LABEL[del.category] || del.category}</b> · {fmt(del.amount)}{del.description ? (' · ' + del.description) : ''}? This can’t be undone.</div>
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
                <button style={btn(false)} onClick={() => setDel(null)}>Cancel</button>
                <button style={btn(true)} onClick={() => doDeleteTxn(del)}>Delete</button>
              </div>
            </div>
          </FModal>
        )}
        {form && !form.asset && (
          <FModal title={form.id ? 'Edit transaction' : (form.kind === 'income' ? 'Record income' : 'Record expense')} onClose={() => setForm(null)}>
            <div style={{ padding: 22, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
              <label style={{ gridColumn: 'span 2' }}><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>CATEGORY</div>
                <select style={inp} value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{(form.kind === 'income' ? INC_CATS : EXP_CATS).map(c => <option key={c} value={c}>{CAT_LABEL[c] || c}</option>)}</select></label>
              <label><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>AMOUNT (UGX)</div><input style={inp} value={form.amount || ''} onChange={e => setForm({ ...form, amount: e.target.value })} placeholder="250,000" /></label>
              <label><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>DATE</div><input style={inp} type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} /></label>
              <label><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>METHOD</div><select style={inp} value={form.method || 'cash'} onChange={e => setForm({ ...form, method: e.target.value })}>{['cash', 'bank', 'mtn', 'airtel', 'cheque'].map(m => <option key={m} value={m}>{m}</option>)}</select></label>
              {form.kind === 'expense' && form.category === 'salaries' && (
                <label style={{ gridColumn: 'span 2' }}><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>PAID TO · TEACHER</div>
                  <select style={inp} value={form.payeeEmail || form.payeeName || ''} onChange={e => { const v = e.target.value; const t = teachers.find(x => (x.email || x.full_name) === v); setForm({ ...form, payeeEmail: (t && t.email) || '', payeeName: (t && t.full_name) || v }); }}>
                    <option value="">— choose teacher —</option>
                    {teachers.map((t, i) => <option key={i} value={t.email || t.full_name}>{t.full_name}{t.email ? (' · ' + t.email) : ''}</option>)}
                  </select></label>
              )}
              {form.kind === 'expense' && form.category !== 'salaries' && (
                <label style={{ gridColumn: 'span 2' }}><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>PAID TO (optional)</div><input style={inp} value={form.payeeName || ''} onChange={e => setForm({ ...form, payeeName: e.target.value })} placeholder="e.g. Kampala Hardware Ltd" /></label>
              )}
              {form.kind === 'expense' && (
                <div style={{ gridColumn: 'span 2' }}><div style={{ fontSize: 11, color: T.ink2, marginBottom: 6, fontFamily: T.mono }}>PAYMENT TYPE</div>
                  <div style={{ display: 'flex', gap: 8 }}>
                    {[['instant', 'Instant payment', 'Generates a receipt'], ['longterm', 'Long-term', 'Goes to bank statement (pending)']].map(([v, t, sub]) => {
                      const on = (form.payType || 'instant') === v;
                      return <button key={v} onClick={() => setForm({ ...form, payType: v })} style={{ flex: 1, textAlign: 'left', border: '1px solid ' + (on ? T.red : T.border), background: on ? 'rgba(220,40,40,0.06)' : 'transparent', color: T.ink, borderRadius: 9, padding: '9px 11px', cursor: 'pointer' }}><div style={{ fontSize: 12.5, fontWeight: 600 }}>{t}</div><div style={{ fontSize: 10.5, color: T.ink3 }}>{sub}</div></button>;
                    })}
                  </div>
                </div>
              )}
              <label style={{ gridColumn: 'span 2' }}><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>{form.kind === 'expense' ? 'PURPOSE / NOTE' : 'DESCRIPTION'}</div><input style={inp} value={form.description || ''} onChange={e => setForm({ ...form, description: e.target.value })} placeholder={form.kind === 'expense' && form.category === 'salaries' ? 'e.g. June salary' : 'e.g. Repair of P3 roof'} /></label>
            </div>
            <div style={{ padding: '0 22px 18px', display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <button style={btn(false)} onClick={() => setForm(null)}>Cancel</button>
              <button style={btn(true)} onClick={() => saveTxn(form)} disabled={busy}>{busy ? 'Saving...' : (form.id ? 'Save changes' : 'Record')}</button>
            </div>
          </FModal>
        )}
        {form && form.asset && (
          <FModal title="Add asset" onClose={() => setForm(null)}>
            <div style={{ padding: 22, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
              <label style={{ gridColumn: 'span 2' }}><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>NAME</div><input style={inp} value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="e.g. School bus UAR 218V" /></label>
              <label><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>CATEGORY</div><select style={inp} value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{ASSET_CATS.map(c => <option key={c} value={c}>{c}</option>)}</select></label>
              <label><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>VALUE (UGX)</div><input style={inp} value={form.value || ''} onChange={e => setForm({ ...form, value: e.target.value })} placeholder="45,000,000" /></label>
              <label><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>CONDITION</div><select style={inp} value={form.condition} onChange={e => setForm({ ...form, condition: e.target.value })}>{['good', 'fair', 'poor'].map(c => <option key={c} value={c}>{c}</option>)}</select></label>
              <label><div style={{ fontSize: 11, color: T.ink2, marginBottom: 5, fontFamily: T.mono }}>ACQUIRED</div><input style={inp} type="date" value={form.acquired || ''} onChange={e => setForm({ ...form, acquired: e.target.value })} /></label>
            </div>
            <div style={{ padding: '0 22px 18px', display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <button style={btn(false)} onClick={() => setForm(null)}>Cancel</button>
              <button style={btn(true)} onClick={() => saveAsset(form)} disabled={busy}>{busy ? 'Saving...' : 'Add asset'}</button>
            </div>
          </FModal>
        )}
      </div>
    );
  }
  return { Finance };
})();
